matrix-org/complement

- dockerfiles/dendrite.yaml
It was missing, causing issues.
Done with a community hat:
```
Signed-off-by: Travis Ralston <travis@t2bot.io>
```
> Add e2e_key db to dendrite config

- README.md
- internal/client/client.go
- internal/federation/handle.go
- internal/must/must.go
- tests/media_nofilename_test.go
One of hopefully many PRs to add the media tests to Complement.
Tested with Dendrite and passes.
Done with a community hat:
```
Signed-off-by: Travis Ralston <travis@t2bot.io>
```
> Add the media_nofilename tests

- tests/user_query_keys_test.go
Synapse allows this test case due to lack of type checking but
Dendrite rejects it. This form (or a variant of it) is used by
iOS clients.
> /client/r0/keys/query: Ensure 400 on non-spec input

- dockerfiles/Dendrite.Dockerfile
This uses the new `--ci` flag in matrix-org/dendrite@28d62244 to produce sane defaults for testing rather than having to `sed` them.
> Use --ci flag in Dendrite generate-config

- dockerfiles/Dendrite.Dockerfile
I found that when building the dendrite docker image, the build process will exit prematurely if `apt install` doesn't receive a confirmation.
```
$ docker build -t complement-dendrite -f Dendrite.Dockerfile .
Sending build context to Docker daemon   16.9kB
Step 1/14 : FROM golang:1.13-stretch as build
---> 89c634cd9763
Step 2/14 : RUN apt-get update && apt-get install sqlite3
---> Running in 68910f2a1eda
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [53.0 kB]
Get:3 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [2410 B]
Get:6 http://security.debian.org/debian-security …
```
> Prevent the Dendrite dockerfile from exiting prematurely

- dockerfiles/synapse/homeserver.yaml
`/data` is a volume in the Synapse docker image. Volumes are not copiedover when committing a container to an image (this resulted in https://github.com/matrix-org/synapse/issues/8421, where we saw that running Synapse instances seemed to lack the users we had just created on them in the blueprint stage). Thus, we should store the database somewhere else, so that it is copied correctly when a blueprint is used for a single test run.
An alternative fix is to just not create a volume (we don't need it when running complement tests), however this would require creating an separate dockerfile from the one we're using from the Synapse repo now, which is much more annoying.
> Store synapse's database somewhere other than a volume

- dockerfiles/synapse/homeserver.yaml
This is necessary until homeserver containers can get access to the dummy CA that's used to create the certificate Complement federation instances are using. Synapse can't trust those entities over federation until this happens, so let's disable verification for now.
A proper fix should be possible after #28 or similar lands.
> Turn off certificate verification for Synapse temporarily

- internal/client/client.go
Hi,
this looked like a good first-issue :)
Fixes #31
> Prevent empty access_token (#31)

- tests/rooms_state_test.go
As Synapse would otherwise complain that the provided body (of nothing) would not be JSON:
```
client.go:200: Making POST request to http://localhost:33066/_matrix/client/r0/createRoom?access_token=xxx
client.go:200: Request body: null
client.go:266: POST /_matrix/client/r0/createRoom => 400 Bad Request (8.18542ms)
client.go:200: HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json
Date: Mon, 09 Nov 2020 13:34:38 GMT
Server: Synapse/1.22.1
41
{"errcode":"M_BAD_JSON","error":"Content must be a JSON object."}
0
```
I …
> TestRoomCreationReportsEventsToMyself: Provide an empty json dict to /createRoom instead of no body

- dockerfiles/Synapse.Dockerfile
- internal/config/config.go
To help out poor homeservers like Synapse which take some time to start up the python interpreter. Otherwise tests become flaky as the homeserver only starts up quick enough around half the time.
> Up the default version check iterations from 50 to 100

- internal/federation/server.go
Fixes https://github.com/matrix-org/complement/issues/32
Causes the federation server to return a `Content-Type` header with a value of "application/json" by default for all requests. Exceptions to this rule should override the header in their handler function.
I've confirmed that Dendrite still passes all tests even with this change.
> Federation: return 'Content-Type' header of 'application/json' by default 

- README.md
- dockerfiles/ComplementCIBuildkite.Dockerfile
- internal/docker/builder.go
- internal/federation/server.go
- tests/main_test.go
This PR adds support for CA generation in complement.
The Outbound Federation server will create a CA cert either in `$PWD/ca` or if run in CI in the Volume mounted to `/ca`.
On container deploy, depending on CI or not, either `$PWD/ca` is bind mounted to `/ca` or the `/ca` Volume of complement is mounted to `/ca` in homeserver containers.
> Add CA generation and mount it to /ca in containers

- internal/instruction/runner.go
This allows passing query parameters to a request while executing an instruction.
This will be useful for e.g sending `server_name` query parameters while attempting to join a room.
I've confirmed that Dendrite still passes all tests even with this change.
> Add request query parameter map to instruction struct

- internal/client/client.go
These methods are analogous with their `CSAPI.MustDo` equivalents other than that they require an expected status code to be specified.
This is a convenience to be used when making calls that we expect with return a non-2xx HTTP status code.
> Add CSAPI.MustDoWithStatus(Raw) method

- internal/client/client.go
- tests/federation_room_get_missing_events_test.go
- tests/federation_room_join_test.go
- tests/federation_room_send_test.go
This PR adds a `serverName` argument to `CSAPI.JoinRoom`, allowing clients to populate [the `server_name` query parameter](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-join-roomidoralias).
Additionally useful for homeservers that don't parse server names from room IDs.
Fixes: https://github.com/matrix-org/complement/issues/39
Aside: I didn't put any newlines between logical blocks of code as the rest of the codebase doesn't do this, even though I sort of wanted to. Is there a general code style for complement defined anywhere?
> Allow specifying server_name parameter values when joining a room

- internal/docker/builder.go
- internal/docker/deployer.go
Closes #41
Since multiple errors can happen when constructing the blueprint, the `ConstructBlueprints` will log all of them and return the first.
> Abort test if the blueprint construction failed

- internal/federation/server.go
- internal/federation/server_room.go
When performing a `/send_join` request, Complement was responding with 'null' entries for `prev_events` and `auth_events` inside of the state events. Instead of `null`, these should've been empty arrays. It came down to nil slices being inserted into interfaces and `json.Marshal` turning those into `null` values instead. Synapse choked on this, leading to the need to track down the bug.
Thanks to @Kegsay who tracked down the causes so quickly!
> Fix null prev_events and auth_events fields from being sent to homeservers

- internal/federation/handle.go
Add a handler which can accept a federation transaction, validate the PDUs and return errors in the case of failing to process a given PDU.
EDUs are accepted but we currently don't do anything with them.
This grew out of trying to fix `TestOutboundFederationIgnoresMissingEventWithBadJSONForRoomVersion6` for Synapse. The test would fail because as soon as Synapse joined the room, it would start trying to send presence EDUs to the new server. Rather than disabling presence, I thought it would be better to write a proper handler for it.
I'll use this handler for that test (and possibly others) in a separate PR.
> Add a handler for federation transactions

- tests/media_nofilename_test.go
Fixes https://github.com/matrix-org/complement/issues/49
By checking just the mimetype instead of an exact string match, homeservers are allowed to add charsets and other directives if they choose. As long as the mimetype stays the same, we're happy.
A comment on the original issue states that the spec is a bit vague about this, and that ideally it would be more explicit about what should happen here. At the moment though this is all we're going to test as it matches the expected behaviour from homeservers.
cc @turt2live
> Check the mimetype, not the whole Content-Type header on media download

- tests/federation_room_get_missing_events_test.go
- tests/federation_room_send_test.go
Updates the following tests to use the new transaction handler introduced in #47:
* `TestOutboundFederationSend` - This test failed with Synapse with the inline transaction handler. Not entirely sure why, the handler function was just never called.
* `TestOutboundFederationIgnoresMissingEventWithBadJSONForRoomVersion6` - Synapse will attempt to send presence to the remote homeserver. The test would fail if not expecting this.
Based on ~~#47.~~
> Update tests to use the new federation transaction handler

- dockerfiles/synapse/homeserver.yaml
We were starting to hit rate limiting in longer tests (like knocking).
The same is essentially done in Sytest: https://github.com/matrix-org/sytest/blob/6e08c8f1744134f9148d3802b070968d308d7abe/lib%2FSyTest%2FHomeserver%2FSynapse.pm#L191-L227
> Disable ratelimiting in Synapse

- .golangci.yml
- build/README.md
- build/scripts/find-lint.sh
- internal/federation/handle.go
This PR adds a find-lint.sh script in a new `build/scripts/` directory, similar to [Dendrite](https://github.com/matrix-org/dendrite/tree/master/build/scripts).
I also realised during this PR that the `DENDRITE_LINT_CONCURRENCY` env var mentioned in Dendrite's find-lint.sh script doesn't actually get used anywhere :) 
Have fixed that in this one, and will PR a fix to Dendrite's after this one is approved.
I also had a couple other things to fix:
- We were accidentally setting the default lint concurrency to 4 CPUs, when really it should be number of available system CPUs.
- Some unlinted code got into master since the lint PR (#52) last had master merged into it. So I've fixed those up here as well.
The intention for this script is to be called by both developers and by CI. Reviewable …
> Add find-lint.sh script

- tests/user_query_keys_test.go
See https://github.com/matrix-org/complement/issues/38 for context.
Ended up having to use `synapse_blacklist` instead of `synapse-blacklist` as golang doesn't allow `-` to be part of build tags.
> Add user_query_keys_test.go to Synapse's blacklist

- build/scripts/find-lint.sh
- tests/federation_room_join_test.go
Moved this script around towards the end of its development, and didn't notice that the depth of it had changed. The things you miss when you don't have CI :)
Also fixed one more lint error that came up. No idea why that wasn't an issue before.
> Fix incorrect path in find-lint script

- tests/federation_room_join_test.go
Once again Synapse likes to send presence when it joins a room. I wonder if we should perhaps make `federation.HandleTransactionRequests(nil, nil)` the default for new servers, with the ability to override it if desired?
The only thing I worry about there is that you may want a test that 404's on transactions.  Maybe at that point we could just extend HandleTransactionRequests to return custom responses.
> Handle transactions sent during UnverifiableEvents test

- tests/msc2946_test.go
Depends on https://github.com/matrix-org/dendrite/pull/1724
> Add MSC2946 fed test

- internal/federation/server.go
Complement was creating TLS certs without SubjectAltName for its federations server.
This most likely causes TLS validation to fail.
This PR adds a DNS or IP field to SubjectAltName depending on whether `docker.HostnameRunningComplement` is an IP or not.
> Fix complemenet SubjectAltName for local cert

- dockerfiles/SynapseWorkers.Dockerfile
- dockerfiles/synapse/caddy.complement.json
- dockerfiles/synapse/workers-shared.yaml
This PR adds a new Dockerfile containing the configuration for a Synapse running in worker mode. Some additional files were required to support the image.
1. A caddy binary needed to be placed in the container for termination TLS requests on the federation port (thanks to Conduit for the idea!). The included file is a Caddy config json file.
2. A shared config file to hand to each Synapse worker was necessary. This file is subtley different from [dockerfiles/synapse/homeserver.yaml](https://github.com/matrix-org/complement/blob/master/dockerfiles/synapse/homeserver.yaml), though it may be nice to have both files be derived from a shared file in the future.
The intention of this is to add testing of Synapse in worker mode to Complement's CI. It is paired with …
> Add a new dockerfile for worker-mode synapse

- README.md
Add docs for getting started writing your own Complement tests
> Add docs for getting started writing your own Complement tests

- dockerfiles/synapse/homeserver.yaml
- dockerfiles/synapse/workers-shared.yaml
This PR enables experimental support for knocking in Synapse. This is to allow Synapse to test itself against the [knocking tests](https://github.com/matrix-org/complement/blob/master/tests/msc2403_test.go).
> Enable experimental knocking support in Synapse

- tests/msc2403_test.go
This tests the ["Changes regarding the Public Rooms Directory"](https://github.com/Sorunome/matrix-doc/blob/soru/knock/proposals/2403-knock.md#changes-regarding-the-public-rooms-directory) section of knocking MSC2403.
Essentially boiling down to:
* Knock rooms can be added to and appear in the public room directory.
* Clients see a `join_rule` entry in the room result to know whether to knock or not to knock. It really is the question.
> Test knock rooms appear in the public room directory

- build/scripts/find-lint.sh
- dockerfiles/synapse/homeserver.yaml
- dockerfiles/synapse/start.sh
- internal/b/blueprints.go
- internal/b/hs_with_application_service.go
- internal/docker/builder.go
- internal/docker/deployer.go
- internal/docker/deployment.go
Add application service support to blueprints
- Only supports defining a basic app service
- In tests, you can use the app service `as_token` to interact with the homserver API
- Does not support defining the `namespaces` part of the app service registration config
- Does not support a mocked/stubbed actual app service that the homeserver calls back to at the `URL`
Split out from https://github.com/matrix-org/complement/pull/68
---
- https://matrix.org/docs/guides/application-services
- https://matrix.org/docs/spec/application_service/r0.1.2
> Add application service support to blueprints

- build/scripts/find-lint.sh
Fix lint script to run on macOS
See
- `-v` only supported in newer bash 4.2 or above: https://unix.stackexchange.com/a/212192/52320
- How to test for environement variable existence, https://stackoverflow.com/a/13864829/796832
- No-op `:`: https://unix.stackexchange.com/a/287867/52320
Before: 
```sh
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
$ ./build/scripts/find-lint.sh
./build/scripts/find-lint.sh: line 22: conditional binary operator expected
$ COMPLEMENT_LINT_CONCURRENCY=1 ./build/scripts/find-lint.sh
./build/scripts/find-lint.sh: line 22: conditional binary operator expected
```
After:
```
$ ./build/scripts/find-lint.sh
No issues found :)
$ COMPLEMENT_LINT_CONCURRENCY=1 ./build/scripts/find-lint.sh …
```
> Fix lint script to run on macOS

- internal/federation/server.go
This PR contains two fixes, separated by commit.
1. Add Subject information to Complement's CA and ephemeral certificates. Federation clients will not accept a certificate if they are unable to get the details of the CA that issued them. It looks for this information in the longterm CA cert.
2. The longterm cert would expire after 5 hours. It is not regenerated if it already exists. Federation clients will not accept expired certificates. I've updated the expiration to 10 years.
Because the longterm CA certificate is not regenerated if it already exists, people will need to clear the old certificates (located in `/tests/ca/`) to generate a new certificate.
Note: I think for 1. information is only required for the CA cert, but I've added the same to the ephemeral cert just in case.
> Fixes to Complement's Federation Certificate

- tests/msc2403_test.go
We've since allowed knock->knock transitions in [MSC2403](https://github.com/matrix-org/matrix-doc/pull/2403/commits/49a72862a93d814219968cff814ff63926181645).
The mainline implementation has been [updated](https://github.com/matrix-org/synapse/pull/6739/commits/44b502644bc4e0473e3734349459bebd2cff0e17) as well.
> Update MSC2403 test to allow knock->knock transitions

- dockerfiles/ComplementCIBuildkite.Dockerfile
This adds libolm-dev to the CI dockerfile, while this is an fairly old libolm release we don't really need a newer one to generate identity and one-time keys. The -dev package includes the shared library and the headers.
> CI: Add libolm-dev to the CI dockerfile

- .gitignore
- README.md
- cmd/account-snapshot/README.md
- cmd/account-snapshot/internal/blueprint.go
- cmd/account-snapshot/internal/redact.go
- cmd/account-snapshot/internal/sync.go
- cmd/account-snapshot/main.go
- internal/b/blueprints.go
- internal/b/perf_e2ee_room.go
- internal/instruction/runner.go
This PR:
- Adds `./cmd/account-snapshot` - see the README.
- Fixes some lint naming issues
- Tweaks the instruction runner to `/login` if the user already exists in the blueprint (e.g logging in on a different device).
> Add account snapshot binary

- dockerfiles/synapse/homeserver.yaml
This option has been deprecated: https://github.com/matrix-org/synapse/blob/master/UPGRADE.rst#blacklisting-ip-ranges
It is recommended to replace it with the similarly named `ip_range_blacklist`.
> Update Synapse IP range blacklist option

- cmd/account-snapshot/internal/blueprint.go
- cmd/homerunner/main.go
- cmd/homerunner/setup.go
- dockerfiles/DendritePostgres.Dockerfile
- internal/config/config.go
- internal/docker/builder.go
- internal/instruction/runner.go
This does a few things.
Instruction runner:
- Add support for hitting `/leave` and `/invite`
- Split out concurrency for user creation and room creation (the former is CPU bound, the latter is not)
- Add an atomic bool for terminating workers on failure.
- Make failures not fail everything if `bestEffort` is set.
Postgres image:
- Increase max conns to 2000
- All components get 100 conns
Account snapshot:
- Change the ordering of events when making blueprints to stop us getting errors.
> Homerunner and instruction runner tweaks

- cmd/account-snapshot/internal/blueprint.go
- cmd/account-snapshot/internal/redact.go
- cmd/account-snapshot/main.go
- internal/b/blueprints.go
- internal/docker/builder.go
- internal/instruction/runner.go
`Blueprint.KeepAccessTokensForUsers []string` will, if set, add labels for the
given user IDs containing their access tokens. Prior to this, we would do this
for all users, but for blueprints with 100k users this made Docker sad.
`--anon-only`, if set on `./account-snapshot`, will output the intermediate
anonymised state prior to blueprint creation, useful for getting snapshots
from people without losing too much information.
> Add Blueprint.KeepAccessTokensForUsers and add --anon-only for account snapshot

- README.md
Tests are not the only reason Complement may run a homeserver image. Blueprints, used by tests, are images that are created by spinning up a homeserver image, creating rooms and users, before snapshotting the state of the container. The resulting snapshot image is then used in tests. Blueprints can also use other blueprints as a base.
Thus homeserver images should not be built on the assumption that the command in the `ENTRYPOINT` or `CMD` dockerfile instruction will only be run once.
> Note that homeserver images must assume entrypoints can be run multiple times

- README.md
The script has been updated in https://github.com/matrix-org/synapse/pull/9685 to support running from local Complement checkouts.
> Update README with info on reworked synapse complement.sh script

- ONBOARDING.md
- README.md
This re-organizes the README and ONBOARDING docs a bit to (in my opinion) be a bit more readable.
For the readme it tries to tell you how to run tests, then how to do development.
For onboarding, it tries to first explain concepts and then how to do that.
I'd like to cross-reference bits of this with links too, but figured I'd throw this up as is for now. Hopefully my mental model on what some of these are isn't completely wrong.
> Re-organize README and ONBOARDING docs

- dockerfiles/synapse/homeserver.yaml
- internal/client/client.go
- tests/msc3083_test.go
This tests matrix-org/synapse#9735 by creating a room that requires membership of a space to join, then attempts to join it (which will fail), then joins the space, then joins the room (which now succeeds).
> Test MSC3083 - joining a restricted room.

- .github/workflows/ci.yaml
We don't run the Complement Buildkite pipelines for external pull requests due to security concerns around passing the Docker socket through to the container.
...there's no such concern on GitHub's public build infrastructure :)
> Use GitHub Actions for linting and testing

- README.md
- this pr adds a GitHub ci badge for the actions which are incorporated in the following project
> chore: add GitHub actions CI status badge

- tests/msc2946_test.go
- tests/msc3083_test.go
This fixes matrix-org/synapse#9756 by updating the Complement tests to match the current specification. The main differences are:
* There's no longer a `limit` flag.
* The summary only travels "down" to children rooms from the given root.
* The path specifies the unstable identifier in it.
Note that this won't break Dendrite because Dendrite was not passing the tag to run these tests.
> Update the Spaces Summary tests (MSC2946) to match the current spec

- tests/msc3083_test.go
This builds on #98 to add tests for matrix-org/synapse#9800.
The tests are pretty much the same, as #98, but the users are no longer on the same server.
> MSC3083: Add additional tests for joining over federation.

- internal/docker/builder.go
- internal/docker/deployer.go
- tests/main_test.go
Every `Deploy()` call used to create a network and the deploy the containers.
It took 4s per network and 4s for containers, so 8s for single HSes, 12s for
federated deployments. Both the networks and containers got torn down at the
end of the test via `Destroy()`.
We don't need to re-create networks all the time. It is sufficient to just
make the network once (similar to how we execute blueprints once per run)
and then clean everything up at the *end of all the tests*. This PR does
just that.
Back of the envelope calculations:
```
Number of Deploy() calls: 23
Number of unique blueprints (hence networks): 4
Number of repeat Deploy() calls: 23-4 = 19
Savings per full Complement run: 19*4 = 76s
```
Also added in logs for `Deploy()` calls to keep an eye on any regressions.
> Speed up Complement runs

- tests/apidoc_login_test.go
- tests/apidoc_presence_test.go
- tests/apidoc_register_test.go
- tests/apidoc_request_encoding_test.go
- tests/apidoc_version_test.go
- tests/federation_keys_test.go
- tests/federation_query_profile_test.go
- tests/federation_room_get_missing_events_test.go
- tests/federation_room_join_test.go
- tests/federation_room_send_test.go
- tests/main_test.go
- tests/media_nofilename_test.go
- tests/msc2403_test.go
- tests/msc2836_test.go
- tests/msc2946_test.go
- tests/msc3083_test.go
- tests/rooms_state_test.go
- tests/user_query_keys_test.go
It's always been a weird quirk that you need to specify a unique namespace string when
deploying containers. This is for parallel tests such that if 2 tests deploy
BlueprintAlice they get unique container names.
This PR changes the API so that we just increment an atomic
counter and use that as the namespace.
> Use atomic ints for namespaces

- tests/msc2946_test.go
- tests/msc3083_test.go
~~Based on #99~~
Blocked on FCP matrix-org/matrix-doc#1772.
> Test against stable MSC1772 spaces identifiers

- tests/msc3083_test.go
Fixes #112 by calling `t.Helper()` and not exporting functions.
Some of these fixes might also apply in `msc2403_test.go` (I see some of those functions don't call `t.Helper()`, but I'm unsure if they should).
> Update helper functions to follow best-practices

- internal/client/client.go
- tests/apidoc_login_test.go
- tests/apidoc_presence_test.go
- tests/apidoc_register_test.go
- tests/apidoc_request_encoding_test.go
- tests/federation_room_join_test.go
- tests/msc2403_test.go
- tests/msc2946_test.go
- tests/msc3083_test.go
- tests/user_query_keys_test.go
This PR changes the `Client` API to reduce the number of functions in it. This has grown organically as the need for query params, raw bodies and custom content types has arisen in tests. Tests can now add as much or as little as they want via the use of functional options which we already use in places like the `match` package.
This removes a number of public `Client` functions:
- `MustDoWithStatus`
- `MustDoWithStatusRaw`
- `MustDoRaw`
- `DoWithAuth`
- `DoWithAuthRaw`
- `Do`
- `DoRaw`
This adds the following public `Client` functions:
- `MustDoFunc`
- `DoFunc`
This adds the following functional options:
- `WithQueries`
- `WithJSONBody`
- `WithContentType`
- `WithRawBody`
Tests which use `MustDo` need no changes as that function has not been altered.
By default, we now use Authorization …
> BREAKING: Use functional options for Client

- dockerfiles/SynapseWorkers.Dockerfile
This PR updates Complement's Synapse worker-flavoured docker image in a few ways:
* Updates the base image name from `synapse:workers` to `synapse-workers`, as it's built from a separate Dockerfile from the base `matrixdotorg/synapse` image.
* Update the `SYNAPSE_WORKERS` env var name to `SYNAPSE_WORKER_TYPES`
* Switches to an explicit list of worker names. We dropped the `*` functionality after adding sharding capabilities. The worker configuration mirrors [that of sytest](https://github.com/matrix-org/sytest/blob/7d297956d6c5a177d2ea492ce6561b2e2500b291/lib/SyTest/Homeserver/Synapse.pm#L657-L1051).
These changes grew out of [this PR on Synapse](https://github.com/matrix-org/synapse/pull/9162/) which changed the base image.
I'd ideally like feedback from the Synapse team on the chosen …
> Update the Synapse Worker configuration with new base image name and worker configuration

- dockerfiles/SynapseWorkers.Dockerfile
- dockerfiles/synapse/workers-shared.yaml
> Fixes for running Synapse in worker mode.

- tests/msc3083_test.go
This adds some additional tests for [MSC3083](matrix-org/matrix-doc#3083) for ensuring that the space summary works for restricted rooms.
See matrix-org/synapse#9922 for the Synapse implementation.
> Add a test for restricted rooms appearing in the spaces summary (MSC3083).

- tests/msc2946_test.go
Corresponds to matrix-org/synapse#10109. This is going to fail until we do a release. 😢
> Add tests to ensure that invite-only rooms only show for invited/joined users in the space summary

- tests/msc3083_test.go
#107 did this already, but I think I had competing PRs or something. Not sure how this got in there!
> Remove an errant unstable MSC1772 prefix from tests.

- ONBOARDING.md
- internal/federation/server.go
- tests/federation_room_get_missing_events_test.go
- tests/msc2836_test.go
This was unused; let's remove it for clarity.
> Remove redundant `hsName` param from `FederationClient`

- tests/msc2403_test.go
Updates knocking tests to use stable:
* Prefixes
* Room versions
* Endpoints
I chose not to remove the build flag since it allows servers to opt into it being enabled.
> Use stable prefixes / endpoints for knocking.

- README.md
- dockerfiles/Synapse.Dockerfile
- dockerfiles/synapse/start.sh
This is super useful if you're trying to bisect for where a bug got introduced (or fixed, in my case...)
> Allow running against older Synapse releases

- README.md
I ran into some trouble getting Complement to run on an M1 Mac. It wasn't able to find libolm - which was installed using brew. Thanks to @tulir, this fixed it!
> Added Apple Silicon instructions to README

- tests/msc2946_test.go
- tests/msc3083_test.go
This is a subset of #123 and corresponds to matrix-org/synapse#10256, which is the straightforward change to only recurse into spaces, not the bit about trimming unnecessary events.
> Do not recurse into non-spaces in the spaces summary.

- tests/federation_room_get_missing_events_test.go
See matrix-org/synapse#10275, current Synapse develop fails unless this is disabled.
> Blacklist a test to match sytest.

- tests/msc3083_test.go
This was broken by matrix-org/synapse#10272
> Fix race in MSC3083 TestRestrictedRoomsRemoteJoin

- tests/federation_room_get_missing_events_test.go
This test got blacklisted for the release of Synapse 1.37.1.
We can't assume that homeservers will process inbound federation events synchronously.
In this particular case we replace the check for errors in /send response with a check that if we send a new event that references the expected rejected event we'll see a request for that event come in.
c.f. matrix-org/synapse#10275 and matrix-org/sytest#1061
> Fix 'Outbound federation will ignore a missing event with bad JSON for room version 6'

- internal/client/client.go
- internal/docker/deployment.go
Add homeserver name to client request logging to differentiate which homeserver is being talked to
Before:
```
=== CONT  TestBackfillingHistory
client.go:356: GET /_matrix/client/r0/sync => 200 OK (31.496008ms)
client.go:356: POST /_matrix/client/unstable/org.matrix.msc2716/rooms/!GkmAGvcDmllsuqLgZA:hs1/batch_send => 200 OK (96.308307ms)
client.go:356: POST /_matrix/client/r0/join/!GkmAGvcDmllsuqLgZA:hs1 => 200 OK (808.747133ms)
client.go:356: GET /_matrix/client/r0/rooms/!GkmAGvcDmllsuqLgZA:hs1/messages => 200 OK (83.415512ms)
```
After:
```
=== CONT  TestBackfillingHistory
client.go:357: GET hs1/_matrix/client/r0/sync => 200 OK (29.885812ms)
client.go:357: POST hs1/_matrix/client/unstable/org.matrix.msc2716/rooms/!jbwgZJKNOedwNWRdop:hs1/batch_send => 200 OK (96.173807ms)
client.go:357: …
```
> Add homeserver name to client request logging to differentiate which homeserver is being talked to

- go.mod
- tests/federation_room_join_test.go
> Check for unauthed events via send_join

- tests/federation_room_join_test.go
This test still fails on Dendrite because it actually doesn't do this check.
> Tweak ban test to make it clearer

- go.mod
- internal/federation/server.go
- tests/federation_room_join_test.go
- tests/msc2403_test.go
Add some tests that try sending things other than proper events via `send_{join,knock,leave}`
> Test validation on `send_{join,knock,leave}`

- ONBOARDING.md
- internal/config/config.go
- internal/docker/deployment.go
Add option to always print server logs.
When working on https://github.com/matrix-org/complement/pull/68, I would just put a `true` in their manually but seems useful to have an actual option to use.
> Add option to always print server logs

- ONBOARDING.md
Document how to hook up Element to the resultant homeservers from running Complement tests.
Spawned from https://github.com/matrix-org/complement/pull/68
> Document how to hook up Element to the resultant homeservers from Complement

- tests/federation_room_join_test.go
- tests/msc2403_test.go
Synapse and Dendrite disagree what the join rules are if this is omitted.
Dendrite follows the spec, Synapse doesn't. Nontheless, we should be
specific in tests.
Also, actually fix the /v1 tests to unmarshal into the right data structure.
You can't use `map[string]interface{}` for v1 due to it sending back an
array of `[200, {}]` instead.
> Always specify a preset

- .github/workflows/ci.yaml
- ONBOARDING.md
- README.md
- tests/csapi/account_change_password_pushers_test.go
- tests/csapi/account_change_password_test.go
- tests/csapi/account_deactivate_test.go
- tests/csapi/apidoc_device_management_test.go
- tests/csapi/apidoc_login_test.go
- tests/csapi/apidoc_presence_test.go
- tests/csapi/apidoc_profile_avatar_url_test.go
- tests/csapi/apidoc_profile_displayname_test.go
- tests/csapi/apidoc_register_test.go
- tests/csapi/apidoc_request_encoding_test.go
- tests/csapi/apidoc_room_create_test.go
- tests/csapi/apidoc_room_state_test.go
- tests/csapi/apidoc_version_test.go
- tests/csapi/main_test.go
- tests/csapi/rooms_state_test.go
- tests/csapi/sync_filter_test.go
- tests/csapi/user_query_keys_test.go
This allows them to run in parallel with federation tests when using `go test ./...`
Add a copy of `main_test.go` with the `PackageNamespace` set to `csapi`. This will be factored out in another PR.
Effectively fixes #119
On my machine before, a run of Complement on Dendrite would take ~360s. Now it takes 240s:
```
ok  	github.com/matrix-org/complement/tests/csapi	148.571s
ok  	github.com/matrix-org/complement/tests	239.968s
```
> Move CSAPI only tests to tests/csapi

- .github/workflows/ci.yaml
I was wondering why #172 was only failing on buildkite and not on GHA. Turns out we run with different build tags. 🤦
> Sync build tags with buildkite.

- ONBOARDING.md
Add tip about being able to log and debug a bunch of variables without the formatting hassle
Spawned from https://github.com/matrix-org/complement/pull/68
> Add tip about being able to log and debug a bunch of variables without the formatting hassle

- tests/msc2716_test.go
Adapt MSC2716 implementation to use chunk events
See https://github.com/matrix-org/synapse/pull/10432
> Adapt MSC2716 implementation to use chunk events

- .github/workflows/ci.yaml
This matches matrix-org/pipelines#158, but for GHA.
The code is cribbed from matrix-org/synapse#10160, and made somewhat homeserver-agnostic, but it seems that Dendrite actually pulls the code it needs as part of building the Docker image, so it is quite different.
This fixes the tests in #145
> Attempt to pull the corresponding Synapse branch when running tests.

- tests/msc3083_test.go
This tests what happens if a server is unable to authorize a room join (due to not being able to invite users or not being able to check the proper allowed rooms).
Corresponds to matrix-org/synapse#10447
~~Based on #145~~
> Test failover logic for MSC3083

- tests/msc3083_test.go
To correspond with matrix-org/synapse#10449.
This should not be merged until [MSC3289](https://github.com/matrix-org/matrix-doc/pull/3289) is merged.
> Use stable room version 8 for MSC3083 tests.

- tests/msc2946_test.go
This adds tests for matrix-org/synapse#10549.
I opted to not remove the old tests for now since both endpoints are going to exist in conjunction right now. We should remoe those in the future when removing support for the old endpoint.
> Test the updated MSC2946 room hierarchy endpoint.

- .github/workflows/ci.yaml
When the `master` branch of complement is built we want to run against the *default homeserver branch*, not the `master` branch (which will most likely always exist).
Fixes #184
> Fix the build for the master branch for synapse.

- tests/msc3083_test.go
- tests/restricted_rooms_test.go
This is a clean-up due to updates of MSC3083 over time. The rooms in the `allowed` list for a restricted room do not need to be a space, just another room. I've updated the tests to relax this a bit, which will hopefully clarify the tests.
> Restricted rooms (MSC3083) do not require spaces.

- tests/restricted_rooms_test.go
Corresponds to matrix-org/synapse#10933.
> Do a clearer join -> join transition for restricted rooms tests.

- internal/b/blueprints.go
- internal/federation/server.go
- internal/federation/server_room.go
- tests/federation_room_event_auth_test.go
We should make sure that events that refer to rejected events in their
auth_events are themselves rejected.
See https://github.com/matrix-org/synapse/issues/9595, and the fixes at https://github.com/matrix-org/synapse/pull/10956.
> Test auth of events with rejected auth_events

- tests/msc2716_test.go
Allow sending no `?state_events_at_start` when user is already part of the current room state (MSC2716).
Synapse changes in https://github.com/matrix-org/synapse/pull/11188
Part of MSC2716: https://github.com/matrix-org/matrix-doc/pull/2716
> Allow sending no `state_events_at_start` when user is already part of the current room state (MSC2716)

- internal/must/must.go
- tests/restricted_rooms_test.go
The sub-tests make it clearer which parts of the test are failing and which are succeeding.
This also adds `MatchSuccess` and `MatchFailure` for wider checks of whether something had failed or not (it's either in the HTTP 200 range or it isn't), rather than checking specific error codes.
> Use sub-tests for restricted join tests

- cmd/homerunner/README.md
- cmd/homerunner/main.go
- cmd/homerunner/setup.go
- internal/config/config.go
- internal/docker/builder.go
- internal/docker/deployer.go
The new name is clearer and easier to understand. Fixes #232.
Currently, Complement will still accept the old env var but will log a Deprecated
warning. Homerunner will just look for the new env var HOMERUNNER_SPAWN_HS_TIMEOUT_SECS
and will ignore the old env var.
> Replace COMPLEMENT_VERSION_CHECK_ITERATIONS with COMPLEMENT_SPAWN_HS_TIMEOUT_SECS

- tests/msc2716_test.go
Part of MSC2716: https://github.com/matrix-org/matrix-doc/pull/2716
Related to https://github.com/matrix-org/synapse/issues/11241
Split off from https://github.com/matrix-org/complement/pull/221
> Make sure historical state events don't come down incremental `/sync` (MSC2716)

- tests/csapi/apidoc_room_create_test.go
- tests/csapi/push_test.go
- tests/csapi/room_ban_test.go
This adds 3 miscellaneous sytests;
- Rooms can be created with an initial invite list (SYN-205)
- Getting push rules doesn't corrupt the cache SYN-390
- Non-present room members cannot ban others
> Add 3 sytests

- tests/federation_keys_test.go
I was taking a cursory glance at `federation_keys_test.go`, and comparing it with its sytest equivalent, when i noticed that the bare test would slip through a lot of potential problems, type mismatches, and other invariants.
I've cleaned those up a little, but some decisions are a bit opinionated.
> Improve federation_keys_test.go

- internal/client/client.go
- internal/federation/server.go
- tests/federation_room_get_missing_events_test.go
- tests/federation_room_join_test.go
- tests/federation_room_send_test.go
- tests/msc2836_test.go
When we are creating a test room on the Complement server, use the same version
as the server defaults to.
> Use server's default room version to create new rooms

- internal/client/client.go
- internal/match/json.go
- tests/csapi/ignored_users_test.go
Reproduces matrix-org/synapse#11506.
Leaving this as a draft until I fix the issue in Synapse. Sticking up a PR for now to see what Dendrite does.
Also note:  fd3a555  is cherry-picked from #237
> Test that invites from ignored users are omitted from incremental syncs

- internal/client/client.go
- tests/csapi/apidoc_room_create_test.go
- tests/csapi/apidoc_room_members_test.go
- tests/csapi/ignored_users_test.go
- tests/csapi/room_ban_test.go
- tests/csapi/rooms_state_test.go
- tests/csapi/user_directory_display_names_test.go
- tests/federation_room_event_auth_test.go
- tests/msc2403_test.go
- tests/msc2716_test.go
- tests/restricted_rooms_test.go
See https://github.com/matrix-org/complement/issues/271 for the rationale why this is being changed. All affected tests have been updated.
Using functional options similar to `client.MustDoFunc`, API usage now looks like:
Initial sync:
```go
bob.InviteRoom(t, roomID, alice.UserID)
alice.JoinRoom(t, roomID, nil)
alice.MustSyncUntil(t, client.SyncReq{}, client.SyncJoinedTo(alice.UserID, roomID))
```
Incremental sync:
```go
since := alice.MustSyncUntil(t, client.SyncReq{TimeoutMillis: "0"}) // get a since token
bob.InviteRoom(t, roomID, alice.UserID)
since = alice.MustSyncUntil(t, client.SyncReq{Since: since}, client.SyncInvitedTo(alice.UserID, roomID))
alice.JoinRoom(t, roomID, nil)
alice.MustSyncUntil(t, client.SyncReq{Since: since}, client.SyncJoinedTo(alice.UserID, roomID))
```
The full …
> Re-design client.SyncUntil

- tests/csapi/invalid_test.go
This adds;
```
./tests/80torture/03events.pl:test "Event size limits",
./tests/80torture/10filters.pl:test "Check creating invalid filters returns 4xx",
./tests/80torture/20json.pl:test "Invalid JSON floats",
./tests/80torture/20json.pl:test "Invalid JSON integers",
./tests/80torture/20json.pl:test "Invalid JSON special values",
```
The remaining 4 aren't added cuz of this problem; https://github.com/matrix-org/complement/issues/258
The filter test is disabled on dendrite because of https://github.com/matrix-org/dendrite/issues/2067
> Add 5 torture tests

- internal/client/client.go
Add request query parameters to Complement request debug logs (`COMPLEMENT_DEBUG=1`), https://github.com/matrix-org/complement/blob/master/ONBOARDING.md#i-think-complement-is-doing-something-weird-can-i-get-more-logs
Before:
```
msc2716_test.go:899: Making POST request to http://localhost:57176/_matrix/client/unstable/org.matrix.msc2716/rooms/%21WfOaOcxJTCHBxspVgq:hs1/batch_send
msc2716_test.go:899: Request body: {"events":[{"content":{"body":"Historical 0 (batch=0)","msgtype":"m.text","org.matrix.msc2716.historical":true},"origin_server_ts":1638404618714,"sender":"@maria:hs1","type":"m.room.message"}],"state_events_at_start":[{"content":{"displayname":"some-display-name-for-@maria:hs1","membership":"join"},"origin_server_ts":1638404618714,"sender":"@maria:hs1","state_key":"@maria:hs1","ty …
```
> Add request query parameters to Complement request debug logs

- tests/msc2716_test.go
Send marker events in all federation tests 🎯
The marker event is important to let remote homeservers know there are historical messages at the given insertion event it points to.
It's just a lucky happen-stance that the tests passed before without the need for the marker event. Marker events are required/expected in order for the history to be properly visible on remote homeservers.
Part of MSC2716: https://github.com/matrix-org/matrix-doc/pull/2716
Split out from https://github.com/matrix-org/complement/pull/214
> Send marker events in all federation tests (MSC2716)

- tests/msc2716_test.go
Put all federation tests under a `Federation` section.
To avoid conflicts, I made this as a follow-up to https://github.com/matrix-org/complement/pull/248 so the diff from that PR is within this one as well. The extra new commit on this PR just indents the tests.
```diff
--- FAIL: TestImportHistoricalMessages (22.74s)
--- FAIL: TestImportHistoricalMessages/parallel (8.01s)
--- SKIP: TestImportHistoricalMessages/parallel/TODO:_Trying_to_send_insertion_event_with_same_`next_batch_id`_will_reject (0.00s)
--- SKIP: TestImportHistoricalMessages/parallel/TODO:_What_happens_when_you_point_multiple_batches_at_the_same_insertion_event? (0.00s)
+         --- PASS: TestImportHistoricalMessages/parallel/Federation (0.00s)
+             --- PASS: …
```
> Put the federation tests under their own section be able to filter (MSC2716)

- tests/csapi/apidoc_room_alias_test.go
This adds a bunch of tests related to Canonical Aliases (splitting up 2 sytests), and 3 related to deleting aliases in various ways, and 1 wrt listing it.
Sytests cleared;
```
./tests/30rooms/05aliases.pl:multi_test "Canonical alias can be set",
./tests/30rooms/05aliases.pl:multi_test "Canonical alias can include alt_aliases",
./tests/30rooms/05aliases.pl:test "Alias creators can delete alias with no ops",
./tests/30rooms/05aliases.pl:test "Alias creators can delete canonical alias with no ops",
./tests/30rooms/05aliases.pl:test "Deleting a non-existent alias should return a 404",
./tests/30rooms/05aliases.pl:test "Only room members can list aliases of a room",
```
> Add 13 alias tests (clearing 6 sytests)

- tests/csapi/apidoc_room_create_test.go
This adds;
- `Can /sync newly created room`
- `POST /createRoom ignores attempts to set the room version via creation_content`
> Add 2 sytests and de-boilerplate `apidoc_room_create_test.go`

- tests/csapi/apidoc_room_history_visibility_test.go
This adds;
```
./tests/30rooms/51event.pl:test "/event/ does not allow access to events before the user joined",
./tests/30rooms/51event.pl:test "/event/ on joined room works",
./tests/30rooms/51event.pl:test "/event/ on non world readable room does not work",
```
But also 4 other tests.
All 7;
> **TestFetchEvent:**
> Fetches an event after join, and succeeds.
> sytest: /event/ on joined room works
> **TestFetchHistoricalJoinedEventDenied:**
> Tries to fetch an event before join, and fails.
> history_visibility: joined
> sytest: /event/ does not allow access to events before the user joined
> **TestFetchHistoricalSharedEvent:**
> Tries to fetch an event before join, and succeeds.
> history_visibility: shared
Skipped in dendrite: https://github.com/matrix-org/dendrite/issues/617
> …
> Add 7 history visibility tests (3 sytests)

- internal/docker/deployer.go
- internal/docker/volumes.go
Fix CA mount problems in local dev
Fix https://github.com/matrix-org/complement/pull/283#discussion_r783448724
1. Fix mount type not being defined on for the CA cert bind mount:
```
failed to deployBaseImage: Error response from daemon: invalid mount config for type "": mount type unknown
```
1. Fix CA volume being created even when the `COMPLEMENT_CA` environment variable isn't defined which leads to `unable to load certificate` errors because `/ca/ca.crt` does not exist.
```go
logrus.WithFields(logrus.Fields{
"mounts": fmt.Sprintf("%+v", mounts),
}).Error("ContainerCreate")
```
---
```
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Images built; running complement
2022/01/12 14:50:45 config: &{BaseImageURI:complement-synapse …
```
> Fix CA mount problems in local dev

- tests/federation_room_ban_test.go
Currently fails on Synapse. Passes on Dendrite.
> Add regression test for matrix-org/synapse#1563

- internal/federation/handle.go
The [spec](https://spec.matrix.org/v1.1/server-server-api/#put_matrixfederationv1send_joinroomideventid) is explicit that the response to `/send_join` should give "The resolved current room state *prior* to the join event", so make that so.
> Fix `/send_join` response

- .github/workflows/ci.yaml
- internal/docker/builder.go
- internal/docker/volumes.go
- internal/federation/handle.go
- internal/federation/server.go
- tests/federation_query_profile_test.go
- tests/federation_room_event_auth_test.go
- tests/federation_room_get_missing_events_test.go
- tests/federation_room_join_test.go
- tests/media_nofilename_test.go
- tests/msc2836_test.go
- tests/room_hierarchy_test.go
Instead, listen on a random OS-allocated high numbered port then
do a switcheroo on the `ServerName` so it reads correctly e.g
`host.docker.internal:56185`. This means the server name will be
invalid if it is read before `Server.Listen()` is called so we now
guard common access points in `Server` which rely on the server
name and fail tests if the server is not yet listening when those
functions are called. To further guard against misuse of server
name whilst it isn't valid, turn it into a private field.
As of this PR, it will now (in theory) be possible to scale out tests indefinitely as we no longer have any central point/resource which all tests rely on. This should make it possible to split `/tests` into more packages which make sense from a Matrix PoV.
Indirectly fixes …
> Don't listen on :8448 for the Complement federation server

- README.md
- dockerfiles/Synapse.Dockerfile
- dockerfiles/SynapseWorkers.Dockerfile
- internal/docker/deployer.go
Rebasing https://github.com/matrix-org/complement/pull/236 
Wait for healthcheck (if it exists) to return OK before checking version endpoint; In all cases, ensure the version endpoint is available before starting.
Users with an image containing a healthcheck they do not want to use can make a tweak to their container by adding
```
HEALTHCHECK NONE
```
to their docker file.
>  Alter container startup to wait for container healthcheck to OK.

- internal/federation/server.go
- internal/must/must.go
- tests/federation_room_get_missing_events_test.go
Requires a few extra helpers which will be used in other federation tests.
> Add /get_missing_events test

- tests/msc2836_test.go
Previously, `/send` on Dendrite was sync, but now it is async. This
made this race manifest itself as it directly hit `/event_relationships`
after `/send` when it should be waiting for it to be processed first.
> Fix MSC2836 test race

- dockerfiles/Dendrite.Dockerfile
- dockerfiles/DendritePostgres.Dockerfile
I was getting the below errors when trying to build the Dendrite docker images, and I noticed that Dendrite was just bumped to Go 1.16 in matrix-org/dendrite#2122, so figured these needed updating as well ☺️
```
/go/pkg/mod/github.com/!shopify/sarama@v1.31.0/config.go:681:37: undefined: io.Discard
/go/pkg/mod/github.com/!shopify/sarama@v1.31.0/decompress.go:43:10: undefined: io.ReadAll
/go/pkg/mod/github.com/!shopify/sarama@v1.31.0/decompress.go:55:10: undefined: io.ReadAll
/go/pkg/mod/github.com/!shopify/sarama@v1.31.0/sarama.go:89:29: undefined: io.Discard
note: module requires Go 1.16
```
> Bump Dendrite docker base images to go 1.16

- cmd/homerunner/main.go
- cmd/homerunner/setup.go
- internal/config/config.go
- internal/docker/builder.go
- internal/docker/deployer.go
- internal/docker/deployment.go
- internal/docker/volumes.go
- internal/federation/server.go
- tests/csapi/main_test.go
- tests/main_test.go
- Remove `VolumeCA` as we don't mount the file as a volume anymore.
- Remove `COMPLEMENT_CA` as we always mount regardless of whether or not the Homeserver image uses it.
- Rejig when and where the CA cert/key is made. Now it is automatically made when a `config.Complement` is made.
- Remove unused/redundant params for `deployImage`.
This can be optimised further. Currently, every time an image is deployed we inject the CA files. It would be sneakier to just do this once when a blueprint is made, so that way the files are already there when we deploy the container.
Fixes #65
> Always mount CA certificates and keys using in-memory files

- .github/workflows/ci.yaml
- Look for corresponding branch on Dendrite in addition to Synapse.
- Set `-p 1` to avoid flakey tests.
- Build Dendrite via a Dockerfile in the dendrite repo not the complement repo.
> Tweak Complement GHA support

- internal/docker/deployer.go
Fixes #306.
Now displays messages:
```
=== RUN   TestChangePassword
2022/02/11 12:28:46 WARNING: complement_csapi.alice.hs1 has a named VOLUME /etc/dendrite - volumes can lead to unpredictable behaviour due to test pollution. Remove the VOLUME in the Dockerfile to suppress this message.
```
> Warn about VOLUME

- cmd/homerunner/setup.go
- internal/docker/builder.go
- tests/csapi/main_test.go
- tests/main_test.go
In the early days, Complement would make all known blueprints up front
in `TestMain`, so there was a function called `ConstructBlueprints`.
It soon became obvious that this was inefficient when you wanted to just
run a single test in an IDE, so blueprints became lazily loaded via a new
function `ConstructBlueprintsIfNotExist`. However, we never called this
new function with > 1 blueprint at a time. This PR makes this function
accept a single blueprint.
Whilst debugging flakey Complement deployments, I spotted a logic error
inside `ConstructBlueprints` where it would say that a blueprint was
created if the total number of images matching the complement context
was >= the number of blueprints. This is completely wrong. The blueprint
is only made when the total number of images == the number …
> Refactor blueprint creation

- internal/docker/deployer.go
I don't know what the scoping is for `network.EndpointSettings`.
If by chance it's global then contextual strings are needed to
stop clashes.
Also log networking information.
> Modify endpoint config to take contextual strings

- internal/docker/builder.go
- internal/docker/deployer.go
Otherwise on some machines they can bind to both IPv4 and IPv6
addresses which could cause port confusion. Rather than binding
to 0.0.0.0 which we don't need, just bind to 127.0.0.1.
> Bind HS containers to 127.0.0.1

- dockerfiles/synapse/log_config.yaml
... which means that `docker logs` also logs to stdout, which is much easier to
tesl with.
> Have synapse log to stdout

- README.md
- dockerfiles/synapse/homeserver.yaml
- internal/client/client.go
- internal/docker/deployment.go
- tests/csapi/account_change_password_pushers_test.go
- tests/csapi/account_change_password_test.go
- tests/csapi/account_deactivate_test.go
- tests/csapi/admin_test.go
- tests/csapi/apidoc_device_management_test.go
- tests/csapi/apidoc_login_test.go
- tests/csapi/ignored_users_test.go
- tests/csapi/user_directory_display_names_test.go
Requires homeservers to use 'complement' as the shared secret. This is very similar to sytest which also uses this endpoint to register admins so it can test admin endpoints: https://github.com/matrix-org/sytest/blob/develop/tests/10apidoc/01register.pl#L304
Manually tested on dendrite/synapse and it works, assuming dendrite is running https://github.com/matrix-org/dendrite/pull/2194
> Support registering as an admin via shared secrets 

- dockerfiles/synapse/homeserver.yaml
- go.mod
- go.sum
- internal/must/must.go
- tests/federation_room_join_test.go
MSC3706 adds extensions to `/send_join` for partial state. Here we add a test which checks the response is correct. (The test is skipped if the server does not support it).
Tests the implementation which was introduced in https://github.com/matrix-org/synapse/pull/11967
~~Requires https://github.com/matrix-org/gomatrixserverlib/pull/291~~
> Test for partial-state responses from /send_join

- dockerfiles/synapse/homeserver.yaml
- dockerfiles/synapse/workers-shared.yaml
- tests/csapi/admin_test.go
Tests for https://github.com/matrix-org/dendrite/pull/2180
> Add tests for server notices

- tests/msc2716_test.go
Use MSC2716 room version that exists (revert back to `org.matrix.msc2716v3`)
During the development of https://github.com/matrix-org/synapse/pull/11243
we added a `org.matrix.msc2716v4` room version but it's no longer necessary
and was removed in https://github.com/matrix-org/synapse/pull/11243/commits/e2928b54a2b4359f6034b6d557c7f36512747ec3
It's okay that `FAIL: TestImportHistoricalMessages/parallel/Unrecognised_prev_event_ID_will_throw_an_error` is failing. Just haven't decided on what error code is correct for that situation. All the other tests are passing ✅
```
$ COMPLEMENT_ALWAYS_PRINT_SERVER_LOGS=1 COMPLEMENT_DIR=../complement ./scripts-dev/complement.sh TestImportHistoricalMessages
...
--- FAIL: TestImportHistoricalMessages (20.32s)
--- FAIL: TestImportHistoricalMessages/parallel …
```
> Use MSC2716 room version that exists (revert back to `org.matrix.msc2716v3`)

- tests/msc2716_test.go
Update Complement to match the error specified in Synapse, see https://github.com/matrix-org/synapse/blob/54e74cc15f30585f5874780437614c0df6f639d9/synapse/rest/client/room_batch.py#L135-L140
```
SynapseError: 400 - No auth events found for given prev_event query parameter. The prev_event=['$some-non-existant-event-id'] probably does not exist.
```
> Update expected response status code when we provide an unrecognised `prev_event` (MSC2716)

- dockerfiles/synapse/start.sh
Fix `Unrecognised appservice access token` errors
Regressed in https://github.com/matrix-org/complement/commit/7f19337e4af84bad8bc596c048d70fa19c779b95 (https://github.com/matrix-org/complement/pull/304)
In https://github.com/matrix-org/complement/pull/304, the appservice mount path changed from `/appservices/` to `/complement/appservice/` but [`start.sh`](https://github.com/matrix-org/complement/blob/53e90f7502ac3c9f1cce7c057ac65562124031d5/dockerfiles/synapse/start.sh#L8) which loops through every file at that path and adds an entry in `homesever.yaml` was not updated.
Before run:
```diff
$ COMPLEMENT_ALWAYS_PRINT_SERVER_LOGS=1 COMPLEMENT_DIR=../complement ./scripts-dev/complement.sh TestImportHistoricalMessages
[+] Building 0.6s (18/18) FINISHED
=> [internal] load build definition from …
```
> Fix `Unrecognised appservice access token` errors

- dockerfiles/Synapse.Dockerfile
Crossref: matrix-org/synapse#12118
I have made this script a proper entry point, so it appears as an suffixless executable.
> Update complement to use setuptools entrypoints

- tests/csapi/room_messages_test.go
Note: TestRoomMessagesLazyLoading and TestRoomMessagesLazyLoadingLocalUser are distinct, because the latter actually replicates the sytest, and the former does some more sane testing (imo)
> Add room-messages; 5 sytests & 1 extra

- tests/csapi/apidoc_version_test.go
This has an opinionated section, even though the spec doesnt really strictly mandate version strings in an explicit sense, i thought it is reasonable to add a regex matcher in here.
> Improve versions test a bit

- tests/csapi/room_messages_test.go
`/messages` flakes on dendrite.
> Skip flakey dendrite test

- dockerfiles/synapse/homeserver.yaml
- dockerfiles/synapse/workers-shared.yaml
Synapse PR matrix-org/synapse#12091, when merged, will cause Synapse to refuse to start if registration is enabled without any verification, unless the new config flag `enable_registration_without_verification` is set. This PR adds that flag to complement's configuration so the homeserver will still start for testing.
> Update config in accordance with Synapse #12091

- tests/msc2716_test.go
Add test for non-member state events in `/batch_send` `state_events_at_start`
Tests for https://github.com/matrix-org/synapse/issues/12110
Synapse changes: https://github.com/matrix-org/synapse/pull/12329
> Add test for non-member state events in `/batch_send` `state_events_at_start`

- internal/config/config.go
... to help distinguish it from other certs that fly around.
> Give the CA certificate a "Common Name"

- internal/docker/builder.go
This PR arises from a conversation with @richvdh, who was presumably working on getting Synapse tested in Complement with Postgres and workers.
The blueprint container gets paused and then committed, which leads to the Postgres database being corrupted in the image that gets created. This then leads to slow startup for that container, since Postgres has to do some kind of recovery process.
It seems like it would be better to gracefully stop the container before committing it, so that Postgres doesn't get corrupted in the process.
Docker stops a container by SIGTERMing it (so the process inside the container can theoretically react to that and shut down gracefully), then SIGKILLing if it didn't stop after a timeout.
This PR will use the equivalent of `docker stop` to shut down the …
> Gracefully stop blueprint containers before committing them

- dockerfiles/README.md
The README points to a very old version which doesn't build with latest Complement anymore.
> Bump Dendrite version in Dockerfiles README

- tests/csapi/room_messages_test.go
Add test to make sure `/messages` behaves as expected for non-existent `room_id`'s
Tests for Synapse regression fix: https://github.com/matrix-org/synapse/pull/12683
Issue: https://github.com/matrix-org/synapse/issues/12678
> Add test to make sure `/messages` behaves as expected for non-existent `room_id`'s

- internal/client/client.go
- internal/docker/builder.go
- internal/docker/deployer.go
- internal/docker/deployment.go
- internal/docker/labels.go
- internal/instruction/runner.go
This adds the `DeviceID` created when building the Blueprint to the `client.CSAPI`
> Add `DeviceID` to `client.CSAPI`

- tests/msc2716_test.go
Synapse change: https://github.com/matrix-org/synapse/pull/12718
Part of [MSC2716](https://github.com/matrix-org/matrix-spec-proposals/pull/2716)
We're testing to make sure historical messages show up for a remote federated homeserver even when the homeserver is missing the part of the timeline where the marker events were sent and it paginates before they occured to see if the history is available. Making sure the homeserver processes all of the markers from the current state instead of just when it sees them in the timeline.
Sending marker events as state now so they are always able to be seen by homeservers (not lost in some timeline gap).
Marker events should be sent with a unique `state_key` so that they can all resolve in the current state to easily be discovered.
- If we re-use the …
> Marker events as state - MSC2716

- internal/config/config.go
- internal/docker/deployer.go
Fixes https://github.com/matrix-org/complement/issues/6
This PR adds a new complement env var called `COMPLEMENT_SHARE_ENV_PREFIX`.
This can be set to any string e.g `FOO_`. If it is set, Complement will
look at the host environment for any env var with this prefix. If it finds
it, it will remove the prefix and add it to the Complement container.
For example, with a host env:
```
COMPLEMENT_SHARE_ENV_PREFIX=FOO_
FOO_DENDRITE_TRACE_HTTP=1
```
This will cause `DENDRITE_TRACE_HTTP=1` to be set in the Complement container.
This addresses 2 desires:
- The ability to ad-hoc set debugging env vars when a test is failing
e.g to use `os.Setenv("FOO_DENDRITE_TRACE_HTTP", "1")` in a test to get more logging.
- The ability to pass through arbitrary data to a Synapse container, as requested
by …
> Enable arbitrary env vars to be propagated to Complement containers

- internal/federation/handle.go
> Set the depth of join events returned from `/make_join`

- internal/federation/handle.go
- internal/federation/server.go
- internal/federation/server_room.go
- tests/federation_room_join_partial_state_test.go
Tests https://github.com/matrix-org/synapse/pull/12812
> Test re-syncing state from other servers listed in `/send_join` reply

- .github/workflows/ci.yaml
This is fallout from https://github.com/matrix-org/synapse/pull/12881 — sorry for the trouble.
I've overridden the job name so that it doesn't write out all the env vars into the job name, as that would be ugly.
> Fix CI by building the Synapse-workers image (needed to build the Synapse-Complement image)

- internal/docker/deployer.go
This gives the container a chance to flush out any pending logs, otherwise we can end up with truncated logs.
> Gracefully shut down container when we want logs

- internal/b/blueprints.go
- internal/client/client.go
- internal/federation/server.go
- tests/csapi/sync_test.go
Lots more detail in the code, but this is a regression test for https://github.com/matrix-org/synapse/issues/12864: Synapse would return a 404 from /sync if given a since token which pointed to a redaction of an unknown event.
> Regression test for /sync returning 404 for redactions

- README.md
- internal/docker/deployer.go
This fixes [connectivity problems I was having when running complement](https://github.com/matrix-org/complement/issues/370#issuecomment-1147687179). Oddly, noone else seems to have found this issue, and I don't really understand the underlying machinations.
I'm not sure if this will cause complement to fail in environments whose docker versions are older than 20.10.
> Use `host-gateway` to ensure servers can reach host

- README.md
We seem to have forgotten to document this option, so this PR tries to put that right.
> Document the environment variable pass-through prefix option introduced by #382

- cmd/homerunner/route_create.go
- internal/docker/deployer.go
- internal/docker/deployment.go
> Add a function to restart a deployment

- tests/federation_room_join_partial_state_test.go
When `/sync`ing, the homeserver under test may send presence to the
Complement homeserver. Handle these EDUs by ignoring them.
Blocks CI for https://github.com/matrix-org/synapse/pull/13151
> Allow presence transactions during faster room joins tests

- internal/b/hs_with_application_service.go
- tests/msc3030_test.go
Add test to make sure you can find imported events before room creation
Synapse changes: https://github.com/matrix-org/synapse/pull/13197
MSC3030
> Add test to make sure you can find imported events before room creation - MSC3030

- .gitignore
- cmd/homerunner/README.md
- cmd/homerunner/routes.go
Fixes #398.
This adds a basic /health endpoint to tell us whether the service is up. It doesn't yet perform a readyness check, but that's mostly because the HTTP server is only started *when* homerunner is ready.
> Add /health endpoint

- tests/federation_room_join_test.go
Hopefully fixes https://github.com/matrix-org/synapse/issues/13256
> Ignore presence EDUs during partial state join test

- .gitattributes
- tests/csapi/apidoc_content_test.go
Small fix in TestContent, and added .gitattributes setting so Git doesn't get many modified files when opening the repo in Windows.
> Fix TestContent log argument order.

- tests/federation_room_join_test.go
Application service can join remote federated room without profile set
Synapse changes: https://github.com/matrix-org/synapse/pull/13131 to address https://github.com/matrix-org/synapse/issues/4778
> Application service can join remote federated room without profile set

- tests/restricted_rooms_test.go
This doesn't make it robust enough for Synapse to relax.  There is another race whose details I would like to write down somewhere. Here will do.
----
There is a race of some kind in `Join_should_succeed_when_invited` where:
- Alice invites Bob to a room
- Bob tries to join it, but is told he cannot because he isn't a member of the `allowed_room`. (Synapse doesn't seem to recognise Bob's invite.)
It smells a lot like https://github.com/matrix-org/synapse/issues/13185 (though not exactly the same). I have traced it down to some kind of inconsistent view of the world within Synapse.
```
event_creator1 | 2022-07-13 12:42:03,329 - synapse.access.http.18013 - 450 - INFO - POST-8 - ::ffff:127.0.0.1 - 18013 - {@alice:hs1} Processed request: 0.078sec/0.000sec (0.009sec, 0.000sec) …
```
> Deflake `Join_should_succeed_when_joined_to_allowed_room` subtest of restricted rooms tests

- internal/client/client.go
This will repeat a request until the condition is satisfied.
Intended use: https://github.com/matrix-org/complement/pull/415
> Add WithRetryUntil request opt which can be used with any CSAPI call

- tests/federation_room_join_partial_state_test.go
I'm going to add a test which will involve *multiple* /state and /state_ids
requests, so we need to make the registered handlers more selective.
> Faster joins tests: make request handlers more specific

- tests/room_hierarchy_test.go
The `/hierarchy` response should not return a `room_id` in each entry in the `children_state` array. This ensures we're not using this (and are using the `room_id` from the parent object).
Fixes #416 
For cross-referencing:
* Removing the field from Synapse: [matrix-org/synapse#10946](https://github.com/matrix-org/synapse/issues/10946#issuecomment-1150206341)
* Removing the field from Dendrite: matrix-org/dendrite#2588
> Fix tests to not depend on unspecced `room_id` parameter for each child room.

- .github/workflows/ci.yaml
The default 10 minute timeout is no longer sufficient to run all of the
Synapse tests and is now being hit randomly.
---
CI is currently failing on `main`: https://github.com/matrix-org/complement/runs/7499686661?check_suite_focus=true because of the timeout.
> Raise the timeout for Synapse CI to 12 minutes

- .vscode/settings.json
- internal/federation/server.go
- tests/federation_room_join_partial_state_test.go
- tests/federation_room_join_test.go
Add tests for three cases where a homeserver receives a latest event with missing prev events while it is still resyncing state after a partial join.
Namely:
```
... <-- M <-- A <-- B
```
```
+---------+
v          \
... <-- M <-- A <-- B
```
and
```
+---------+
v          \
... <-- M <-- A <-- B <-- C
```
where event M is the last event the homeserver knows about and the rightmost event is the one it receives.
The last case tests the code path mentioned in https://github.com/matrix-org/synapse/issues/13002
Best reviewed commit by commit.
> Add more tests for receiving events while resyncing for a partial join

- tests/federation_room_join_partial_state_test.go
A few changes:
* make it check the requested `latest_events` to check that we are replying to the request we think we are
* Use the structures in `gomatrixserverlib` rather than defining our own
* General cleanups
> Make `handleGetMissingEventsRequests` more general

- tests/csapi/sync_test.go
When no events are received in the sync window, it tries to access index `-1` and panics.
This mitigates that and also adds some log lines which might be useful in tracking down another flake that occurs rarely.
> Fix an out of bounds error in TestSync 'sync should succeed even if the sync token points to a redaction of an unknown event'

- tests/federation_room_join_partial_state_test.go
A rather complicated test which demonstrated that the infinite loop was in https://github.com/matrix-org/synapse/issues/13001 was possible.
~~The test currently fails: it's getting stuck waiting for soft-fail, which is something @squahtx is working on.~~
> Regression test for infinite-loop-in-resync

- tests/csapi/apidoc_room_state_test.go
- tests/knocking_test.go
This is needed in Synapse because the room directory is updated in the background. Part of https://github.com/matrix-org/synapse/issues/13161.
It's particularly worse when using workers, because the room directory is updated in a different process and CPU contention increases the likelihood of hitting the race.
> Retry /publicRooms a few times to allow for propagation delay before a new room appears in the room directory

- tests/federation_room_join_partial_state_test.go
Factor the creation of the server and the room from `beginPartialStateJoin`. It was handy there, but is too restrictive for tests that need to mess about with the room before the join.
~~Based on #418~~
> partial state tests: factor out room creation

- internal/federation/handle.go
- tests/federation_room_join_partial_state_test.go
Lines up with https://github.com/matrix-org/synapse/pull/13416
> Add test ensuring that /make_join and /send_join are rejected during a partial join

- internal/client/client.go
- tests/csapi/apidoc_room_receipts_test.go
- tests/csapi/room_typing_test.go
> read receipts: ensure that read receipts show up via /sync

- internal/b/blueprints.go
- internal/docker/builder.go
Fixes matrix-org/complement#435
Includes an error handling change to be able to see what's going on when base images aren't available. Before the error handling change, the requests below would have both reported the error:
`{"message":"failed to create deployment: CreateDeployment: Deploy returned error Deploy: No images have been built for blueprint custom"}`
Demonstrating the actual change by making these requests:
`curl -XPOST -d'{"base_image_uri":"not_an_image", "blueprint": { "Name": "custom", "Homeservers": [ { "Name": "hs1", "Users": [], "Rooms": [] }]}}' http://localhost:54321/create`
`{"message":"failed to create deployment: CreateDeployment: Failed to construct blueprint: ConstructBlueprintIfNotExist(custom): failed to ConstructBlueprint: errors whilst constructing blueprint …
> Extend Blueprints to permit baseImageURI to be optionally overridden for each Homeserver

- internal/federation/handle.go
- tests/federation_room_join_partial_state_test.go
A couple more faster-joins tests: one for an event that should have been rejected but was not, and one with an event that should have been accepted but was rejected.
> Tests for events with incorrect auth during faster join

- tests/csapi/admin_test.go
Makes `Alice can join the alert room` more reliable by waiting for the message to come down sync.
> Make server notice test more reliable

- tests/csapi/apidoc_room_state_test.go
Signed-off-by: Andrew Doh <andrewddo@gmail.com>
> add complement test for getting joined_members after leaving.

- tests/federation_room_join_partial_state_test.go
https://github.com/matrix-org/synapse/pull/13477 unblocks lazy-loading
`/sync`s while a room has partial state, which allows us to wait for
received events using `/sync`.
"Resync completes even when events arrive before their prev_events" is
now the only test that waits for events using `/event`, since the
outliers do not appear in the `/sync` timeline.
> Wait for received events using /sync in faster room joins tests

- tests/federation_room_join_partial_state_test.go
These broke during the merge of #441.
> Fix partial state join tests for incorrectly accepted/rejected state

- tests/msc2716_test.go
Use MSC2716v4 room version
Companion changes in Synapse https://github.com/matrix-org/synapse/pull/13551
```
$ COMPLEMENT_ALWAYS_PRINT_SERVER_LOGS=1 COMPLEMENT_DIR=../complement ./scripts-dev/complement.sh -run TestImportHistoricalMessages
--- PASS: TestImportHistoricalMessages (42.92s)
--- PASS: TestImportHistoricalMessages/parallel (16.97s)
--- SKIP: TestImportHistoricalMessages/parallel/TODO:_Trying_to_send_insertion_event_with_same_`next_batch_id`_will_reject (0.00s)
--- SKIP: TestImportHistoricalMessages/parallel/TODO:_What_happens_when_you_point_multiple_batches_at_the_same_insertion_event? (0.00s)
--- PASS: TestImportHistoricalMessages/parallel/Federation (0.00s)
--- PASS: TestImportHistoricalMessages/parallel/Federation/When_messages_have_already_been_scrolled_back_through,_new_his …
```
> Use MSC2716v4 room version

- tests/federation_room_join_partial_state_test.go
Fixes https://github.com/matrix-org/synapse/issues/13564
> Hack around a race in the partial-state tests

- tests/msc3030_test.go
Tests to make sure right event is returned when all of the events have the same timestamps.
Synapse changes: https://github.com/matrix-org/synapse/pull/13658
Part of https://github.com/matrix-org/matrix-spec-proposals/pull/3030
> Tests to make sure right event is returned when all of the events have the same timestamps - MSC3030

- .github/workflows/ci.yaml
- internal/config/config.go
- internal/docker/builder.go
This adds the ability to define homeserver specific base images using environment variables, allowing us to test e.g. Dendrite <> Synapse or Synapse <> Dendrite federation
The images are defined using e.g. `COMPLEMENT_BASE_IMAGE_HS1=complement-synapse COMPLEMENT_BASE_IMAGE_HS2=complement-dendrite`, where `HS1` and `HS2`  are the homservers as defined by the blueprint. If no HS specific image is defined, falls back to `COMPLEMENT_BASE_IMAGE`.
> Add ability to define HS specific base images

- internal/federation/handle.go
> Fix panic in `HandleEventRequests` when room or event is not known

- tests/csapi/device_lists_test.go
Test what happens when local and remote users join and leave rooms.
The previous test only covered local users already in the same room.
> Add more thorough tests for device list tracking

- tests/csapi/apidoc_search_test.go
Adds the tests from tests/43search.pl
> Add `/search` tests

- tests/federation_room_join_partial_state_test.go
This improves runtime of the test file from 3m15s to 1m25s locally.
> Partial State Join tests: Reuse one Alice deployment but register a different alice user for each test

- .github/CODEOWNERS
See documentation at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
Weirdly the latest rule is what "matches", so you put more specific rules later in the file.
I figured it made sense to still have the teams as reviewers so that things don't get blocked -- what do you think?
> Request review of Kegan for complement internals.

- .github/workflows/ci.yaml
It seems like I can't manage to get a valid CI run in https://github.com/matrix-org/complement/pull/463 because of that.
> Raise synapse test timeout to 20mn

- tests/csapi/room_relations_test.go
Basic tests for the `/relations` endpoint from MSC2675.
Part #351.
> Add basic tests for /relations.

- tests/csapi/apidoc_search_test.go
Fixes https://github.com/matrix-org/complement/issues/478, I hope, though there may be other tests with the same problem.
> Allow search results to appear in multiple orders

- internal/match/json.go
Hopefully this will make the errors from `JSONCheckOff` and friends a bit more consistent and comprehensible.
> Improve error messages from JSONCheckOff

- README.md
- internal/config/config.go
- internal/docker/builder.go
- internal/docker/deployer.go
- internal/docker/labels.go
- internal/federation/server.go
- internal/federation/server_test.go
- tests/federation_room_join_test.go
- tests/federation_room_send_test.go
- Podman expects the network name specified when launching the container to match the name used when creating it even when the network ID is specified, the API spec is unclear about that
- Adding labels when committing a container needs to use `changes` query parameter instead of a POST json, which is unspecified
- Add a config to specify the hostname where Complement on the host can be reached when inside a container. Podman uses `host.containers.internal`
> Some changes to calls to Docker API for podman compatibility

- tests/csapi/room_relations_test.go
Builds on #467 to test pagination of `/relations` endpoint, also tests MSC3715 support (forward pagination).
> Test pagination of the `/relations` endpoint.

- tests/federation_room_join_partial_state_test.go
One of the outgoing device list update tests is flaking: https://github.com/matrix-org/synapse/issues/13977
Some extra logging would be helpful.
> Log received `m.device_list_update` EDUs during faster room joins tests

- tests/federation_room_join_partial_state_test.go
`/sync` is not a good way to wait for a room to transition to full
state, since it only waits for the full state at particular events
instead of the whole room. This caused flakiness in the "Device list
updates no longer reach departed servers after partial state join
completes" test.
Use `/members` instead to wait for partial state joins to complete.
---
Fixes https://github.com/matrix-org/synapse/issues/13977.
> Faster room joins: Fix bug in `awaitPartialStateJoinCompletion`

- tests/msc2716_test.go
Be tolerant of the the `end` key not existing in a /messages response. As spec'd:
> If no further events are available (either because we have reached the start of the timeline, or because the user does not have permission to see any more events), this property is omitted from the response.
>
> *-- https://spec.matrix.org/v1.1/client-server-api/#get_matrixclientv3roomsroomidmessages*
Split out from https://github.com/matrix-org/complement/pull/214
Previously, it would throw the following error and potentially we found all of the events within that last response to satisfy everything,
```
JSONFieldStr: key 'end' missing
```
> Be tolerant of the the `end` key not existing in a /messages response

- tests/federation_room_join_partial_state_test.go
Synapse can take a while to persist 100 outliers. Instead of doing one big wait for the last outlier to be persisted, do some smaller waits for intermediate outliers and a small wait for the last outlier.
ie. as long as the homeserver under test is making progress, we are happy to continue waiting.
Fixes https://github.com/matrix-org/synapse/issues/13777.
> Faster room joins: Deflake events-arriving-before-prev_events test

- internal/federation/server.go
Some tests may choose to re-use the same homeserver deployment across
multiple test cases, each spinning up different complement servers.
However, when a complement server happens to have the same hostname and
port as a previous one, the homeserver under test may retain cached keys
for the old complement server and reject events from the new one.
Give each complement server a unique key ID to stop that from happening.
---
Thanks to @erikjohnston for suggesting the fix.
Fixes https://github.com/matrix-org/synapse/issues/13975.
> Use a different key ID for each complement server

- tests/direct_messaging_test.go
Yet another straw to grasp at for debugging https://github.com/matrix-org/synapse/issues/13334
> Enable debug logging for TestWriteMDirectAccountData

- tests/csapi/push_test.go
Adds the tests from tests/61push/06_push_rules_in_sync.pl
> Add pushrule sync tests

- tests/msc3030_test.go
De-flake MSC3030 backfill test with Synapse worker replication
Spawning from https://github.com/matrix-org/synapse/pull/14028#discussion_r987156197
CI failure: https://github.com/matrix-org/synapse/actions/runs/3182998161/jobs/5189731097#step:6:15343 (from [discussion](https://github.com/matrix-org/synapse/pull/14028#discussion_r987156197))
```
WORKERS=1 POSTGRES=1 COMPLEMENT_ALWAYS_PRINT_SERVER_LOGS=1 COMPLEMENT_DIR=../complement ./scripts-dev/complement.sh -run TestJumpToDateEndpoint/parallel/federation/can_paginate_after_getting_remote_event_from_timestamp_to_event_endpoint
```
The reason they failed before was because we're fighting against stale caches across workers racing while waiting for invalidation, see https://github.com/matrix-org/synapse/issues/13185#issuecomment-1269413897 …
> De-flake MSC3030 backfill test with Synapse worker replication

- tests/federation_room_join_partial_state_test.go
Test device list tracking for users incorrectly thought to be in a
partial state room once the room transitions to full state.
---
Built on top of #476.
> Faster room joins: Add edge case tests for device list tracking

- tests/federation_room_join_partial_state_test.go
This change tests device list tracking when a partial state room is left
before the partial state join completes. Leaving a partial state room
is not currently implemented in Synapse.
---
~~Built on top of #475.~~
> Faster room joins: Add abandoned join tests for device list tracking

- sytest.ignored.list
This adds tests from `48admin` which use the `/_synapse` api.
The reason `48admin` wasnt added completely is because `/whois` (a test in 48admin) doesnt use synapse admin apis.
> Ignore more /_synapse tests

- tests/csapi/room_kick_test.go
This adds two sytests:
- `./tests/30rooms/15kick.pl:test "Users cannot kick users from a room they are not in",`
- `./tests/30rooms/15kick.pl:test "Users cannot kick users who have already left a room",`
> Sytest: Add `30rooms/15kick` tests

- tests/csapi/room_threads_test.go
Corresponds to matrix-org/synapse#14175 / matrix-org/synapse#13394.
This needs a test for pagination too, but I haven't had a chance to write that one yet.
> Add basic tests for the /threads endpoint.

- sytest.ignored.list
...as this "test" is just a self-check, which we should already be doing in other parts of complement, so this is not an migratable test.
> Ignore "Checking local federation server" sytest

- internal/instruction/runner.go
...because conduit is very strict with parsing these server names.
> Only send server_name in blueprint joins when it's non-empty

- tests/csapi/apidoc_room_alias_test.go
This essentially ports a retry from sytest that wasn't included in when this was ported to complement: see https://github.com/matrix-org/synapse/issues/14183#issuecomment-1280910298 for the history.
If I had a magic wand, Synapse would provide read-after-write consistency here and the retries would be unnecessary. But it doesn't so I've added them.
Resolves https://github.com/matrix-org/synapse/issues/14183.
> Deflake `GET /rooms/:room_id/aliases lists aliases`

- internal/client/client.go
- tests/csapi/room_profile_test.go
This adds one sytest:
- `./tests/30rooms/22profile.pl:   test "$datum updates affect room member events",`
This also alters `SyncJoinedTo` in a backwards-compatible way to receive additional check functions, to check on the event of the join, this could be useful for things like restricted room joins, or - in this case - checking changed membership profile data.
> Sytest: Add `30rooms/22profile` test

- cmd/sytest-coverage/main.go
- sytest.ignored.list
This:
- Adds a debug (`-d`) flag to `sytest-coverage`, to print unrecognised `"sytest: "`-containing comment lines.
- This is useful for when we update the sytest.list, and tests are removed that were previously added to complement.
- Or, when `"sytest: "`-containing lines are shuffled around or slightly edited, to catch those.
- Removes `Push rules come down in an initial /sync` from the ignored sytest list.
- This test was present in the codebase, and after looking at the corresponding sytest, it seems to have been included by accident in the past, simply due to the wording of the test, and not an introspective of if the test uses deprecated endpoints or not.
Internally:
- This moves over the manual flag recognition to golang `flag`-based handling, which would do a lot of boilerplate …
> Add sytest-coverage debug flag

- tests/direct_messaging_test.go
Reverts matrix-org/complement#493
It looks an awful lot like this fixed the problem... let's back it out to see if it starts happening again.
cf https://github.com/matrix-org/synapse/issues/13334#issuecomment-1290599757
> Revert "Enable debug logging for TestWriteMDirectAccountData"

- tests/csapi/room_typing_test.go
- tests/federation_room_typing_test.go
This adds three sytests:
- `./tests/30rooms/20typing.pl:test "Typing can be explicitly stopped",`
- `./tests/30rooms/20typing.pl:test "Typing notifications also sent to remote room members",`
- `./tests/30rooms/20typing.pl:test "Typing notification sent to local room members",`
> Sytest: Add `30rooms/20typing` tests

- tests/federation_room_typing_test.go
In #510 I seem to have forgotten to add a sytest comment, whoops.
> Add forgotten sytest comment (`20typing`)

- internal/client/client.go
- tests/csapi/to_device_test.go
This adds three sytests;
- `./tests/46direct/01directmessage.pl:test "Can recv a device message using /sync",`
- `./tests/46direct/01directmessage.pl:test "Can send a message directly to a device using PUT /sendToDevice",`
- `./tests/46direct/01directmessage.pl:test "Can send a to-device message to two users which both receive it using /sync",`
This also adds the following to `internal/`:
- `SendToDeviceMessages`, to more easily send to-device messages, in the correct format.
- `SyncToDeviceHas` `SyncCheckOpt`, to check for to-device messages in sync responses.
> Sytest: Add `46direct/01directmessage` tests

- internal/federation/server.go
- tests/federation_query_profile_test.go
This adds two sytests:
- `./tests/50federation/02server-names.pl:test "Non-numeric ports in server names are rejected",`
- `./tests/50federation/10query-profile.pl:test "Inbound federation can query profile data",`
This also adds one generic function, `(*federation.Server).DoFederationRequest`, as a counterpart to `SendFederationRequest`, though with the only difference being that it returns the response instead of trying to JSON-deserialise it.
Note: This function is largely a copy of `SendFederationRequest`, I tried to figure out how I can dedup them into one function, but seeing as they both use different functions from the HTTP Client object, it's probably not possible without having it pass a `func(*gomatrixserverlib.Client)` or likewise to a third internal function.
> Sytest: Add `50federation` / `02server-names` & `10query-profile` remaining tests

- tests/csapi/apidoc_room_state_test.go
- tests/csapi/device_lists_test.go
- tests/csapi/invalid_test.go
- tests/csapi/push_test.go
- tests/csapi/room_relations_test.go
- tests/csapi/rooms_members_local_test.go
- tests/csapi/sync_test.go
- tests/csapi/upload_keys_test.go
- tests/federation_room_ban_test.go
- tests/federation_room_join_test.go
- tests/restricted_rooms_test.go
Seeing as almost all SkipIfs in complement are due to the fact the originating homeservers do not implement the functionality, I did a once-over to check all of them, and paired them with those issues, and standardized the format of `SkipIf` comments along the way.
Like this, the intended way how to skip a test on a homeserver then always comes paired with an issue to watch or resolve to remove that skip, else these skips would bitrot and the related tests aren't executed, potentially hiding non-compliant behaviour.
Furthermore, some tests *did* pass inbetween then and now, those skips have been removed.
> Do once-over on all `SkipIf`s in codebase, adding issue numbers, un-skipping passing tests

- tests/csapi/sync_test.go
This will fail for now, and should be fixed by https://github.com/matrix-org/synapse/pull/14243.
> Add presence test from people in 2 different rooms in incremental sync

- tests/csapi/thread_notifications_test.go
Tests the behavior in matrix-org/synapse#14174, builds on #500.
> Test sending receipts on events related to the root of a thread. 

- internal/web/server.go
- tests/csapi/url_preview_test.go
This follows up on #279, specifically [this](https://github.com/matrix-org/complement/pull/279#discussion_r833158719) comment.
This re-adds the URL preview test, but also adds a basic framework in `internal/web` for those webservers, with example use being displayed in the re-added test.
This PR is related to https://github.com/matrix-org/synapse/pull/14198, which ~~needs to land first before the test can be un-skipped~~ had landed.
> Add "Test URL preview" sytest and basic webserver creation

- internal/federation/server.go
- internal/web/server.go
Per the conversation starting here:
https://matrix.to/#/!alCakyySsFIAVfZLDL:matrix.org/$B_wrGA9l3SwDDuufbOxMw_VyrwH_Vg00coJDRQTG7_8?via=matrix.org&via=element.io&via=sw1v.org
During test cleanup there's no need for us to try to gracefully shutdown---we're about to completely destroy the container anyway.
> Use http.server.Close (not .Shutdown) for cleanup

- tests/federation_room_join_partial_state_test.go
Kegan advises that this will help prevent a class of deadlock we've see (thank you Kegan). See
https://github.com/matrix-org/synapse/issues/14010#issuecomment-1295108331 and https://matrix.to/#/!alCakyySsFIAVfZLDL:matrix.org/$Tk4PR9KGtfCJTFLFW0ecytvFYxf3C_36UW9C5F7fRzE?via=matrix.org&via=element.io&via=sw1v.org
Closes https://github.com/matrix-org/synapse/issues/14010. (Hopefully; we can reopen if needed.)
> Buffer channels in faster joins device list tests

- internal/must/must.go
- tests/csapi/apidoc_server_capabilities_test.go
Resolves #528
This adds three convenience methods, which call eachother for deduplication.
The effective round-trip from gjson.Result.Str to byteslice and back is unfortunate, but it's how `match.JSON` is defined.
> Add `MatchJSON`, `MatchJSONBytes` and `MatchGJSON`

- tests/federation_room_join_partial_state_test.go
Synapse Issue: https://github.com/matrix-org/synapse/issues/13287
Synapse PR: https://github.com/matrix-org/synapse/pull/14292
> Test aliases during a partial join resync

- sytest.ignored.list
- tests/csapi/rooms_state_test.go
This adds the following sytests:
- `./tests/30rooms/01state.pl:test "Joining room twice is idempotent",`
- `./tests/30rooms/01state.pl:test "Setting room topic reports m.room.topic to myself",`
- `./tests/30rooms/01state.pl:test "Setting state twice is idempotent",`
This also fixes a typo in the `sytest.ignored.list`
> Sytest: Add `30rooms/01state` tests

- tests/csapi/sync_archive_test.go
- tests/csapi/sync_filter_test.go
- tests/csapi/sync_test.go
This adds 8 sytests:
- `./tests/31sync/09archived.pl:test "Archived rooms only contain history from before the user left",`
- `./tests/31sync/09archived.pl:test "Left rooms appear in the leave section of full state sync",`
- `./tests/31sync/09archived.pl:test "Left rooms appear in the leave section of sync",`
- `./tests/31sync/09archived.pl:test "Newly left rooms appear in the leave section of gapped sync",`
- `./tests/31sync/09archived.pl:test "Newly left rooms appear in the leave section of incremental sync",`
- `./tests/31sync/09archived.pl:test "Previously left rooms don't appear in the leave section of sync",`
- `./tests/31sync/09archived.pl:test "We should see our own leave event when rejecting an invite, ".`
- `./tests/31sync/09archived.pl:test "We should see our own leave event, …
> Sytest: Add `31sync/09archived` tests

- tests/csapi/sync_test.go
A simple test to verify room summaries are correctly send down sync.
> Add regression test for room summaries

- tests/csapi/apidoc_room_alias_test.go
- tests/federation_room_alias_test.go
This adds 7 sytests:
- `./tests/30rooms/05aliases.pl:test "Can delete canonical alias",`
- `./tests/30rooms/05aliases.pl:test "Regular users can add and delete aliases in the default room configuration",`
- `./tests/30rooms/05aliases.pl:test "Regular users can add and delete aliases when m.room.aliases is restricted",`
- `./tests/30rooms/05aliases.pl:test "Remote room alias queries can handle Unicode",`
- `./tests/30rooms/05aliases.pl:test "Room aliases can contain Unicode",`
- `./tests/30rooms/05aliases.pl:test "Users can't delete other's aliases",`
- `./tests/30rooms/05aliases.pl:test "Users with sufficient power-level can delete other's aliases",`
> Sytest: Add `30rooms/05aliases` tests

- sytest.ignored.list
- tests/csapi/power_levels_test.go
This adds three sytests:
- `./tests/10apidoc/36room-levels.pl:test "GET /rooms/:room_id/state/m.room.power_levels can fetch levels",`
- `./tests/10apidoc/36room-levels.pl:test "PUT /rooms/:room_id/state/m.room.power_levels can set levels",`
- `./tests/10apidoc/36room-levels.pl:test "PUT power_levels should not explode if the old power levels were empty",`
This skips a test called "Both GET and PUT work" because its sole existence in sytest appears to be to prove the ability to set and get powerlevels, for other test's requirements.
> Sytest: Add `10apidoc/36room-levels` tests

- tests/federation_room_join_test.go
For https://github.com/matrix-org/synapse/pull/14442. As noted therein this is a corner-cut PR: I'm trying to do the bare minimum to get it to pass. I'm not trying to write something which thoroughly checks the heroes logic.
> Expect heroes in partial join response

- internal/must/must.go
Encountered while working on another test, seems like I slipped in a bug with this
> MatchGJSON: `jsonResult.Raw` instead of `jsonResult.Str`

- internal/client/client.go
When joining a room, it is erroneous to send an empty POST body.
Send an empty JSON body instead.
---
Similar to #460.
> JoinRoom: send with empty JSON body for spec compliance

- tests/csapi/rooms_members_local_test.go
Depending on timings, the "Existing members see new members' presence"
test in `TestMembersLocal` may see the expected join and presence in an
initial or incremental sync. Both types of sync elicit different
behaviour in homeserver implementations, such as Synapse. Split the test
into initial and incremental sync variants to eliminate the race
condition.
In addition, fix the initial sync case by explicitly setting Bob's
presence to online. The spec does not guarantee that Bob will have a
non-offline presence after merely joining a room, nor does the spec
guarantee that offline presences will show up in initial syncs.
Fixes https://github.com/matrix-org/synapse/issues/13199.
> Fix setup for `TestMembersLocal` tests and split into sync types

- tests/msc2716_test.go
- tests/msc3030_test.go
- tests/room_timestamp_to_event_test.go
Use stable MSC3030 `/timestamp_to_event` endpoints
Synapse changes: https://github.com/matrix-org/synapse/pull/14471
> Use stable MSC3030 `/timestamp_to_event` endpoints

- .gitignore
- cmd/homerunner/Dockerfile
- cmd/homerunner/README.md
- cmd/homerunner/main.go
- internal/config/config.go
- internal/docker/builder.go
- internal/docker/deployer.go
The aim of this PR is to allow homerunner to start servers using docker-dind, and make them available over a non-local network. We can take advantage of this in a k8s environment by running servers on the PodIP, and so make them available outside of the pod.
This is wanted for  trafficlight, where a adapters wrap and automate real clients (eg, ios/android/web) and so running many of them can be heavyweight. Currently we can run everything locally on a single desktop, but managing simultaneous runs of multiple tests needs us to spread the load across hosts.
The change should be a noop for complement run tests, retaining the default behaviour there, and without a configuration option being set, is also a noop for homerunner users.
If we wanted, this could also allow running a homerunner as …
> Homerunner: Permit running HS with remote networking, and provide docker build

- tests/federation_room_join_partial_state_test.go
Since the partial state join tests reuse the same homeserver deployment,
it is important that each test leaves the homeserver in an acceptable
state for subsequent tests. In particular, we must allow in-progress
partial-state joins to complete before tearing down Complement servers,
otherwise the homeserver may mark Complement hostname:port combinations
as offline and refuse to contact them in subsequent tests.
---
These issues have 502 Bad Gateway failures:
Closes https://github.com/matrix-org/synapse/issues/13564.
Closes https://github.com/matrix-org/synapse/issues/14245.
Closes https://github.com/matrix-org/synapse/issues/14543.
> Allow the homeserver to finish partial-state joining before teardown

- .gitignore
[direnv](https://direnv.net/) is a tool to automatically configure your shell in some way when entering a project's directory. I personally use it to activate a [nix flake](https://nixos.wiki/wiki/Flakes) profile - so appropriate tools and native dependencies are installed at the correct version when entering my local complement checkout.
The `.envrc` and `.direnv/` directories are a byproduct of this tool, and aren't meant to be committed to source control, hence adding them to the .gitignore file to make the life of `direnv` users easier.
The same has been done on Synapse: https://github.com/matrix-org/synapse/pull/12335.
> Ignore files generated by the `direnv` development tool

- tests/csapi/apidoc_login_test.go
The `home_server` field in responses to `/register` and `/login` is deprecated since [r0.4.0](https://matrix.org/docs/spec/client_server/r0.4.0.html)
Same as https://github.com/matrix-org/sytest/pull/1325, but removes it completely.
> Remove deprecated `home_server` field

- internal/client/client.go
- tests/msc3391_test.go
This PR adds Complement tests for MSC3391. The MSC is [currently being implemented in Synapse](https://github.com/matrix-org/synapse/pull/14714).
> Add tests for MSC3391

- tests/csapi/push_test.go
- tests/federation_room_join_partial_state_test.go
A number of tests start goroutines that write into channels when completed, however the tests would close the channel if it exited early (e.g. due to a timeout).
Instead, make the goroutine that writes into the channel the one that closes it.
This does mean that the goroutines will continue past the end of the test (?), but they did that before too. I am wondering if there is a better way of doing these things...
> Fix panics due to closed channel in some tests

- internal/client/client.go
- tests/csapi/account_change_password_pushers_test.go
- tests/csapi/push_test.go
Some helper methods to get and set push rules. We also refactor [tests/csapi/push_test.go](https://github.com/matrix-org/complement/pull/577/files#diff-538b85fd27b45b086bd4368eac7da9042a0d290e62de779779792572203037f0) to use them.
> Add `GetAllPushRules`, `GetPushRule` and `SetPushRule` client helper methods

- tests/federation_room_join_partial_state_test.go
part of matrix-org/synapse#12802
- Check that leaves work correctly today, even if they block on resync
- Dummy test that leaves will work before resync completes
- Ideas for future tests
> Baby steps for testing leaves during a faster join

- tests/federation_room_join_partial_state_test.go
Otherwise the test fails if the server receives a presence update during the partial join
> Ignore presence updates in test

- internal/client/client.go
- tests/federation_room_join_partial_state_test.go
> Add a test to verify that the user directory is properly updated after a lazy load join finishes syncing

- internal/client/client.go
- tests/federation_room_join_partial_state_test.go
Based on #584 by @MatMaul.
Matches https://github.com/matrix-org/synapse/pull/14870
> Tests for eager-sync behaviour during and after a partial join

- tests/federation_room_join_partial_state_test.go
Hopefully fixes https://github.com/matrix-org/synapse/issues/14902. In the test, there are two directory lookups, one for a user rod and one for a user todd. When I wrote the test, my assumption was that if rod was showing up in the user directory then todd would show up as well, so I did not retry the lookup for todd. It seems now that I was wrong. I added a retry to todd's lookup, and ran the test ~15 times locally. Not only did it not fail, but I saw several runs where todd's lookup was retried - which in the previous iteration would have been a failure -  so I suspect this was the problem.
> Fix flaky user directory test

- tests/csapi/device_lists_test.go
When a remote user has a device list update, an entry is expected to appear in
`device_lists.changed` in the `/sync` response. The local homeserver may then
query the remote homeserver for the update. Some homeservers (Synapse) may emit
extra `device_lists.changed` updates in `/sync` responses after querying keys.
Previously, we attempted to skip over the spurious `device_lists.changed`
updates by doing another sync. This wasn't sufficient, so we make another
remote user send a device list update, and wait for that to appear.
Fixes #580.
---
Fixes https://github.com/matrix-org/synapse/issues/14103.
> Fix `TestDeviceListUpdates` flakes

- tests/csapi/account_data_test.go
This PR adds tests for getting and setting account data.
The tests correspond to the following sytest tests:
* Can add account data
* Can get account data without syncing
* Can add account data to room
* Can get room account data without syncing
> account data: add test for setting and getting

- tests/federation_room_join_partial_state_test.go
We previously attempted to deflake this test in #490 by waiting longer
for the 100 outlier events to be persisted. This turned out to be
insufficient, as calculating the full state for all 100 events can also
take a while and delay the room's appearance in /sync.
Raise the timeout for waiting for the room to appear in /sync from 5
seconds to 20 seconds. Going off the logs of the failing test runs, it
takes 6 to 10 seconds for the room to appear in /sync.
---
Fixes https://github.com/matrix-org/synapse/issues/13777.
> Faster room joins: Deflake events-arriving-before-prev_events test again

- tests/unknown_endpoints_test.go
Tests the behavior of [MSC3743](https://github.com/matrix-org/matrix-spec-proposals/pull/3743) by querying for unknown endpoints / methods that a homeserver is expected to provide.
> Test response to unknown endpoints.

- internal/client/client.go
- internal/docker/deployment.go
- internal/federation/handle.go
- internal/federation/server_room.go
- tests/csapi/device_lists_test.go
- tests/msc2716_test.go
- tests/room_timestamp_to_event_test.go
While experimenting with Complement and trying to speed up a few things, I noticed some race conditions causing inconsistent results. I started tracking them down one-by-one using the `-race` flag on `go test`. Fixing these allows heavier usage of `t.Parallel()` during tests while sharing a deployment and registering fresh users with `RegisterUser()`(ala, federation_room_join_partial_state_test.go and #471) and it's siblings and derivatives. This alone will not(unfortunately) speed up Complement on Synapse(especially on Github CI), but will pave the way for less odd and inconsistent errors in the future. Hopefully, some flakes will go away as well(looking at you `Client Timeout while awaiting headers`).
Mutex's and RWMutex's were the main go-to, but atomic.AddInt64() was also used in a …
> Increase thread safety on variables

- .ci/complement_package.gotpl
- .ci/scripts/gotestfmt
- .github/workflows/ci.yaml
Skipped tests too. Credit is not mine, just duplicating what I saw in the Synapse repository.
Fixes #589 
Signed-off-by: Jason Little <realtyem@gmail.com>
> Print Complement test failures at the bottom of the test output

- .github/workflows/ci.yaml
Allow running the suite of CI tests without creating a PR. Right now, in order to test a change in Complement, I have to create a Pull Request either against this repo or my own. With this, I can just run it on my personal repo/branch by clicking a button.
Signed-off-by: Jason Little <realtyem@gmail.com>
> Add workflow_dispatch to ci.yaml

- tests/csapi/device_lists_test.go
When a homeserver (Synapse) performs a partial state join to a room, it
may emit `device_lists.changed` entries for users it thinks are in the
room, despite the room not appearing in the /sync response yet. This is
questionable behaviour, but not forbidden by the spec. Once the
homeserver is fully joined to the room, it may emit another round of
`device_lists.changed` entries for users it knows are definitely in the
room.
These extra entries were causing test cases to advance prematurely and
randomly fail. To fix the tests, we explicitly check for join events
alongside the `device_lists.changed` entries produced by joins. In
effect, we ensure that homeservers are fully joined to the test rooms
before continuing the rest of the tests.
For consistency, we also check for leave events …
> Fix `TestDeviceListUpdates` flakes, again

- tests/federation_room_join_partial_state_test.go
See https://github.com/matrix-org/synapse/pull/15068.
IDK if we want Synapse-specific tests in Synapse, but short of https://github.com/matrix-org/complement/issues/226 I think this is the least-bad option.
> Test that Synapse will purge a room during resync

- tests/knocking_test.go
Wait for up to 5 seconds for the knock membership to arrive over
federation before failing the "Users in the room see a user's membership
update when they knock" test case.
---
Fixes https://github.com/matrix-org/synapse/issues/14226.
> Fix `TestKnocking` flakiness by waiting for knock membership to arrive

- tests/federation_room_join_test.go
When performing a federated join, the homeserver accepts a list of
servers to try joining via. When the first remote server in the list is
not in the room, the federated join ought to try the rest of the list
instead of failing immediately.
---
Synapse currently fails the test. https://github.com/matrix-org/synapse/pull/15074 fixes it.
> Add test for failover of federated joins

- tests/restricted_rooms_test.go
The `TestRestrictedRoomsRemoteJoinFailOver` test involves a leave, then
rejoin of a restricted room over federation. Ensure that the remote
homeserver has processed the leave event before trying to rejoin,
otherwise the test will not be testing the intended behaviour.
---
Fixes https://github.com/matrix-org/synapse/issues/14986.
> Fix `TestRestrictedRoomsRemoteJoinFailOver` flake due to race

- tests/csapi/sync_test.go
Remove some checks for fields that are not required in sync responses.
Signed off by Nick @ Beeper (@Fizzadar).
> Don't require optional sync fields in responses

- tests/csapi/apidoc_room_create_test.go
This ports https://github.com/matrix-org/sytest/pull/1216 to complement.
See also
https://github.com/matrix-org/synapse/pull/14884#issuecomment-1403516617
> Don't require room_alias in /createRoom response

- tests/federation_room_join_partial_state_test.go
This
- tests https://github.com/matrix-org/synapse/issues/12802 (which we seem to have got for free by solving https://github.com/matrix-org/synapse/issues/12801)
- Unskips https://github.com/matrix-org/complement/pull/581
Closes https://github.com/matrix-org/synapse/issues/12802
> More tests for leaves during a partial state resync

- tests/csapi/apidoc_room_forget_test.go
Previously, the test would always pass as it did not provide the
`include_leave` option in the room filter and did not check the
`rooms.leave` key in the response.
> Fix test for forgotten rooms not showing up in initial /sync

- tests/csapi/apidoc_room_forget_test.go
> Add test for leaves in forgotten rooms appearing in incremental /sync

- tests/csapi/txnid_test.go
This adds a test which checks that the `transaction_id` is indeed present when querying an event with `/rooms/{roomId}/event/{eventId}`. Synapse implementation was bugged, and I fixed it in matrix-org/synapse#15174
> Add a test which checks that the transaction ID is serialised in the event

- tests/federation_room_join_partial_state_test.go
Many of the faster joins test flakes are due to the homeserver under
test failing to contact Complement homeservers after they have been
torn down. When this happens, subsequent tests can fail if they use a
Complement homeserver that happens to have the same hostname:port as one
which the homeserver under test has previously marked as offline.
Make the homeserver under test leave rooms at the end of each test, so
that it stops trying to contact the Complement homeservers in the room.
---
Reviewable commit by commit.
NB: you can tease out the flakes by forcing Complement to reuse ports whenever possible:
```diff
diff --git a/internal/federation/server.go b/internal/federation/server.go
index ed7974d..4c4ccbe 100644
--- …
```
> Deflake faster joins tests by leaving rooms as part of test cleanup

- tests/csapi/apidoc_register_test.go
Test `/register/available` endpoint for:
1. Available user name
2. Unavailable user name
3. Invalid user name
4. ~Unicode invalid name~ This didn't get past query sanitization, so removed.
[Spec](https://spec.matrix.org/v1.5/client-server-api/#get_matrixclientv3registeravailable)
Why I rubbed these sticks together:
* https://github.com/matrix-org/synapse/issues/15242
Signed-off-by: Jason Little <realtyem@gmail.com>
> Add /register/available tests

- tests/federation_room_join_partial_state_test.go
We need to start expecting leave events before the test user leaves the
room, not after.
Introduced in #626.
> Fix incorrect refactor of Leave during resync faster joins test

- tests/unknown_endpoints_test.go
Now that https://github.com/matrix-org/dendrite/pull/3016 is merged, this test should pass on Dendrite as well.
> Un-skip "UnknownEndpoint" test on Dendrite

- internal/docker/deployer.go
- runtime/hs.go
- runtime/hs_dendrite.go
If we're running Dendrite with coverage enabled, we need to gracefully stop the containers, as otherwise the coverage data can't be written to disk. `ContainerStop` will still kill the container if it fails to stop within 1 second.
As this will be used for every homeserver implementation, an alternative could be to check `runtime.Homeserver` and only always gracefully stop containers if it is Dendrite.
> Gracefully stop containers

- .github/workflows/ci.yaml
> Fix CI by ensuring `gotestfmt` is on PATH, plus cleanups

- internal/client/client.go
- tests/csapi/txnid_test.go
This adds Client-Server API tests relation to transaction identifiers:
1. That requests are idempotent within a single client session
2. That transaction ID can be re-used across client sessions
3. That the transaction ID is present in /sync response to deal with "local echo"
Signed-off-by: Hugh Nimmo-Smith <hughns@element.io>
> Tests for transaction ID semantics

- .github/workflows/ci.yaml
Current version is really old and breaks the CI since Debian Strech is not available anymore.
cf failure [here.](https://github.com/matrix-org/complement/actions/runs/4952393175/jobs/8869014023)
> Update dendrite	build used to check homerunner

- tests/unknown_endpoints_test.go
As of [MSC2246](https://github.com/matrix-org/matrix-spec-proposals/pull/2246), the PUT method is allowed on the `/_matrix/media/v3/upload` endpoint.
See the spec documentation here: https://spec.matrix.org/v1.7/client-server-api/#put_matrixmediav3uploadservernamemediaid
Note that this blocks https://github.com/matrix-org/synapse/pull/15503
> unknown endpoints: allow PUT /_matrix/media/v3/upload

- tests/media_filename_test.go
Fix tests blocking [matrix-org/dendrite#3113](https://github.com/matrix-org/dendrite/issues/3113). NVT#1548992
Signed-off-by: Josh Qou <jqou@icloud.com>
> Fix assert of unsafe media api behaviour

- tests/knock_restricted_test.go
These are disabled for Dendrite because they're not supported there.
> Stabilize knock restricted tests (room v10).

- tests/knock_restricted_test.go
I really thought I did this in #643, but I guess I missed it.
This removes the build flag for the room v10 tests since they're now standard.
> Move knock restricted tests to Dendrite blacklist.

- tests/federation_upload_keys_test.go
We waited for the device list update to come down sync before calling `/keys/query`. However, the update going down sync occasionally was for the *initial* key upload, and so the call to `/keys/query` would return the old key and the test would fail.
To fix that, wait for the initial key to come down sync, and *then* run the test.
Closes https://github.com/matrix-org/synapse/issues/16020 (maybe?)
> Fix flakey key upload test

- tests/csapi/apidoc_room_forget_test.go
These are meant to be required but it seems like they are not in practice...
c.f. https://github.com/matrix-org/synapse/issues/16366
> Add empty request bodies to /forget calls in TestRoomForget

- must/must.go
- should/should.go
- tests/csapi/apidoc_room_alias_test.go
- tests/federation_acl_test.go
The `should` package is a more lenient form of the `must` package, in that it does not fail the test if the assertion fails. Instead, these functions return an error, which the test can then handle.
This is particularly useful in cases where a test needs to retry a certain request. Previously, you had to hand-roll the checks on the response because using `must.MatchResponse` would fail the test, even though it might have been okay as the next retry may pass the matchers.
Fixes https://github.com/matrix-org/complement/issues/546
Tests need to be revisited to see if this can be used in more places.
An example of this. Before:
```go
res = alice.DoFunc(
t,
"GET",
[]string{"_matrix", "client", "v3", "rooms", roomID, "aliases"},
client.WithRetryUntil(
1*time.Second,
func(res *http.Response) …
```
> Add should package

- b/blueprints.go
This is so people can use `b.Event` directly when setting `initial_state` in `/createRoom` - as used in sliding sync tests.
> Add JSON keys to b.Event

- tests/media_filename_test.go
See https://github.com/matrix-org/synapse/pull/16440
> Test content disposition against a content type with a parameter.

- .github/workflows/ci.yaml
- helpers/test_main.go
- tests/msc2836/main_test.go
- tests/msc2836/msc2836_test.go
- tests/msc3391/main_test.go
- tests/msc3391/msc3391_test.go
- tests/msc3874/main_test.go
- tests/msc3874/room_messages_relation_filter_test.go
- tests/msc3890/main_test.go
- tests/msc3890/msc3890_test.go
- tests/msc3902/federation_room_join_partial_state_test.go
- tests/msc3902/main_test.go
- tests/msc3930/main_test.go
- tests/msc3930/msc3930_test.go
This adds more parallelism as a side-effect.
> Remove msc build tags. Add msc packages.

- client/auth.go
- client/client.go
- client/sync.go
- must/must.go
This doesn't cover `t.(Fatal|Error)f?` calls in tests, but I think this by itself would do a lot to make it easy to spot errors.
Par exemple:
> client and must: print errors in red

- tests/msc3890/msc3890_test.go
Regressed in #665.
Also add signposts which were helpful when debugging this test.
> Fix MSC3890 tests using wrong CSAPI helper

- internal/docker/deployment.go
- internal/federation/server.go
- internal/federation/server_test.go
- test_main.go
- test_package.go
- tests/csapi/account_change_password_test.go
- tests/csapi/apidoc_room_receipts_test.go
- tests/csapi/device_lists_test.go
- tests/csapi/url_preview_test.go
- tests/federation_keys_test.go
- tests/federation_room_join_test.go
- tests/federation_room_send_test.go
- tests/msc2836/msc2836_test.go
- tests/msc3902/federation_room_join_partial_state_test.go
- tests/restricted_rooms_test.go
The `docker` package is internal, meaning that it's hard for out-of-repo tests to make use of the `*docker.Deployment`. Instead, hide the concrete impl behind an interface `complement.Deployment`, which also conveniently only exposes the functions used by real tests. Pepper this API with TODOs. Add a `FederationDeployment` which is a subset of `complement.Deployment` required by the complement-fed-server.
This is the first step to enabling dirty runs. Now that the deployment API is defined, this opens up the ability to:
- specify a general "give me a CSAPI" function with functional options for passwords/etc, which will replace `NewUser`, `LoginUser`, `RegisterUser`, `Client`). This function will _not allow the full user ID to be specified_, so dirty runs can add a prefix/suffix to the …
> Add a complement.Deployment interface

- helpers/clientopts.go
- internal/docker/deployment.go
- test_package.go
- tests/csapi/account_change_password_pushers_test.go
- tests/csapi/account_change_password_test.go
- tests/csapi/account_deactivate_test.go
- tests/csapi/admin_test.go
- tests/csapi/apidoc_device_management_test.go
- tests/csapi/apidoc_login_test.go
- tests/csapi/apidoc_logout_test.go
- tests/csapi/apidoc_register_test.go
- tests/csapi/device_lists_test.go
- tests/csapi/ignored_users_test.go
- tests/csapi/keychanges_test.go
- tests/csapi/room_leave_test.go
- tests/csapi/room_typing_test.go
- tests/csapi/rooms_members_local_test.go
- tests/csapi/rooms_state_test.go
- tests/csapi/sync_test.go
- tests/csapi/to_device_test.go
- tests/csapi/txnid_test.go
- tests/csapi/user_directory_display_names_test.go
- tests/msc3890/msc3890_test.go
- tests/msc3902/federation_room_join_partial_state_test.go
Define just 2 functions which can be used universally. By having this as an interface, this also means we keep the door open for matrix-authentication-service to swap out the impl for one which registers with MAS.
The `Login` function requires an _existing_ CSAPI client to work. This is by design to force tests to not hardcode "login as localpart `alice`".
The `Register` function does not do this, and exposes a literal `Localpart` field to set. This will change to a prefix/suffix, but is more involved e.g a test may call `Register("chris")` then later on assert `@chris:hs1` is present somewhere, so all tests need to be sanity checked for this before swapping to prefixes/suffixes). Hence this will be up next in another PR.
> Refactor Deployment Register/Login functions

- helpers/clientopts.go
- internal/docker/deployment.go
- tests/csapi/account_change_password_pushers_test.go
- tests/csapi/account_change_password_test.go
- tests/csapi/account_deactivate_test.go
- tests/csapi/admin_test.go
- tests/csapi/apidoc_device_management_test.go
- tests/csapi/apidoc_login_test.go
- tests/csapi/apidoc_logout_test.go
- tests/csapi/apidoc_register_test.go
- tests/csapi/device_lists_test.go
- tests/csapi/ignored_users_test.go
- tests/csapi/keychanges_test.go
- tests/csapi/room_leave_test.go
- tests/csapi/room_typing_test.go
- tests/csapi/rooms_members_local_test.go
- tests/csapi/rooms_state_test.go
- tests/csapi/sync_test.go
- tests/csapi/to_device_test.go
- tests/csapi/txnid_test.go
- tests/csapi/user_directory_display_names_test.go
- tests/msc3890/msc3890_test.go
- tests/msc3902/federation_room_join_partial_state_test.go
Based on https://github.com/matrix-org/complement/pull/673
This means clients can't register specific localparts, which is good for dirty runs.
TODO: Delete `Deployment.Client` and swap to `Deployment.Register` for standard alice/bob runs.
> Replace Localpart with LocalpartSuffix 

- client/client.go
the given map is the JSON body of the /createRoom request, NOT the "creation content" that the spec speaks of (i.e. the content of the m.room.create event.)
> Fix param name in (Must)CreateRoom

- .github/workflows/ci.yaml
- ENVIRONMENT.md
- internal/config/config.go
- internal/docker/deployer.go
- internal/docker/deployment.go
- test_package.go
- tests/csapi/user_directory_display_names_test.go
This halves the runtime of Synapse tests on SQLite. This will likely be an even bigger improvement on postgres/workers due to the setup time there being even longer.
> Add COMPLEMENT_ENABLE_DIRTY_RUNS to vastly speed up test runs

- tests/csapi/sync_test.go
c.f.  https://github.com/matrix-org/synapse/issues/16463 and https://github.com/matrix-org/synapse/pull/16485
> Add regression test for matrix-org/synapse#16463

- internal/docker/deployer.go
- test_package.go
- tests/csapi/apidoc_room_state_test.go
- tests/msc3902/federation_room_join_partial_state_test.go
Previously, `Deploy(t, 1)` would deploy 1 HS in 1 isolated blueprint which could be reused by other tests who also call `Deploy(t, 1)`. This pattern extended to `Deploy(t, 2)`, which would deploy 2x HSes in 1 isolated blueprint. This however means we'd run more containers in parallel. What's worse: these containers would only be cleaned up at the end of the entire test package run: `defer deployment.Destroy(t)` would do nothing.
This was Very Bad on GHA boxes as they have limited resources, causing synapse/workers to fail to complete.
The cost of this aggressive reuse of dirty containers is slightly more ugliness internally in Complement, as we now entirely have separate code paths for handling dirty stuff. This can be refactored later down the line to demarcate the difference between …
> Make dirty runs dirtier

- .github/workflows/ci.yaml
- go.mod
Synapse tried to build complement using the go version specificed in go.mod, and [failed](https://github.com/matrix-org/synapse/actions/runs/6685687057/job/18164290687?pr=16567#step:7:2616):
```
📦 github.com/matrix-org/complement/internal/docker
Error: internal/docker/deployment.go:29:26: undefined: atomic.Int64
```
See https://github.com/matrix-org/synapse/pull/16567#issuecomment-1784220124 onwards.
> Require go 1.19 for atomic.Int64

- test_main.go
Required for complement-crypto which needs this to tear down containers / processes.
>  Add cleanup function for testing.M

- internal/docker/deployer.go
- internal/docker/deployment.go
- test_package.go
This will be used to test connectivity issues over federation.
> Add Stop/StartServer functions to Deployment

- .github/workflows/ci.yaml
- README.md
Active development now happens in element-hq/synapse.
> Update references to matrix-org/synapse

- tests/federation_room_send_test.go
Based on random conversations, we want to make sure that clients cannot accidentally miss being told about events if an earlier event (earlier in the DAG) arrives interleaved with newer events.
> Add test to check timeline ordering semantics

- federation/server_room.go
- tests/msc3902/federation_room_join_partial_state_test.go
e.g. https://github.com/element-hq/synapse/actions/runs/7423009864/job/20199559386?pr=16782
The flake happened because the test received a PDU during the test clean up, i.e. after we had removed the PDU handler but before the test had finished. During this time a PDU would be received and not handled, resulting in the test being marked as a failure.
The fix is to explicitly wait for the event to be received.
<details>
<summary>Test output</summary>
```
❌ TestPartialStateJoin/EagerInitialSyncDuringPartialStateJoin (1.54s)
client.go:642: [CSAPI] POST hs1/_matrix/client/v3/register => 200 OK (18.557323ms)
federation_room_join_partial_state_test.go:275: Do a one-off initial sync for Alice, so we have a next_batch token for future incremental syncs
client.go:642: [CSAPI] GET …
```
> Fix flakey test `EagerInitialSyncDuringPartialStateJoin`

- client/auth.go
- client/client.go
- client/sync.go
- ct/test.go
- federation/server.go
- federation/server_room.go
- helpers/waiter.go
- internal/docker/deployment.go
- must/must.go
- runtime/hs.go
- test_main.go
- test_package.go
- The entire Complement API now no longer uses `t *testing.T`, instead opting for `ct.TestLike` which is an interface. In practice, this changes nothing. However, this enables Complement to be used in many more places where you do not have a `t *testing.T` object to use e.g benchmarks, scripts. This is of particular use for Complement-Crypto which has to run parts of the test as a standalone binary, and therefore has no `t *testing.T` to use.
- The entire Complement API now uses `ct.Fatalf` and `ct.Errorf` for highlighting test failures in red. This should make it significantly easier to skim for the test failure message.
- Add `Deployment.ContainerID(TestLike, hsName) string` to allow tests to interact with the container beyond the abilities of the Complement API e.g log extraction, …
> refactor: make logging test agnostic and colourful

- client/client.go
- internal/docker/deployment.go
This field isn't really used anywhere, but it is extremely useful to be tagged with the client itself when you want to derive a new client from an existing one. Mostly helpful for Complement Crypto currently.
> Annotate `client.CSAPI` with `.Password`

- client/client.go
- tests/federation_device_list_update_test.go
For https://github.com/element-hq/synapse/issues/11374
> Add device list update regression test

- tests/csapi/sync_test.go
Regression test for https://github.com/element-hq/synapse/issues/16948
> Initial test for the "device lists" part of the `/sync` response

- tests/msc3967/main_test.go
- tests/msc3967/msc3967_test.go
xref https://github.com/element-hq/synapse/pull/16943
> Add tests for msc3967

- tests/csapi/sync_archive_test.go
Ensure that `state` is calculated correctly for archived rooms, even when there are no events returned in the timeline.
cf https://github.com/element-hq/synapse/pull/16932
> Add a regression test for a /sync bug

- tests/msc4115/main_test.go
- tests/msc4115/msc4115_test.go
[MSC4115](https://github.com/matrix-org/matrix-spec-proposals/pull/4115) adds a "membership" field to each event served over the CS API. This PR adds tests for it.
Requires https://github.com/element-hq/synapse/pull/17104
> Test for MSC4115 support

- federation/server_room.go
- match/json.go
- should/should.go
- tests/federation_sync_test.go
And some drive-by logging improvements, along with a new `ServerRoom.WaiterForEvent(eventID)` function which makes waiting for an event to arrive on the Complement server much much easier to write in code.
> Regression test for https://github.com/element-hq/synapse/issues/16928

- dockerfiles/README.md
- runtime/hs.go
- runtime/hs_conduwuit.go
- tests/media_filename_test.go
conduwuit has:
- fully working [Complement support via Nix/Lix flake](https://github.com/girlbossceo/conduwuit/tree/main/nix/pkgs/complement), building the OCI image, [Complement as a flake input](https://github.com/girlbossceo/conduwuit/blob/main/flake.nix#L4)
- Has a [helper script](https://github.com/girlbossceo/conduwuit/blob/main/bin/complement)
- Complement with conduwuit does not require a reverse proxy if using the helper script and Nix/Lix flake for Complement PKI
- [integrated into our CI](https://github.com/girlbossceo/conduwuit/blob/main/.github/workflows/ci.yml#L101-L144) and uploads the OCI image used as an [artifact (`complement_oci_image.tar.gz`)](https://github.com/girlbossceo/conduwuit/actions/runs/9049542800)
- [publishes test …
> Add conduwuit

- client/client.go
- tests/csapi/apidoc_content_test.go
- tests/csapi/media_async_uploads_test.go
- tests/federation_media_content_test.go
- tests/media_filename_test.go
- tests/media_nofilename_test.go
> Add tests for _matrix/client/v1/media/download

- federation/handle.go
This should fix issues where Dendrite attempts to call the authed media endpoint first and only falling back to the legacy media endpoint, as seen [here](https://github.com/matrix-org/dendrite/actions/runs/10125662955/job/28001444870?pr=3397#step:7:54).
> Handle authed media endpoint

- tests/media_thumbnail_test.go
As the title states. https://github.com/element-hq/synapse/issues/17518 was missed because Synapse does not request thumbnails via this endpoint, rather fetches the media over the `/download` endpoint and then generates the thumbnails. This PR adds a test to ensure the basic functionality of the `/thumbnail` endpoint.
> Add a basic test fetching thumbnail from `_matrix/federation/v1/media/thumbnail`

- tests/msc4140/delayed_event_test.go
- tests/msc4140/main_test.go
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
> Start adding tests for MSC4140

- tests/msc4140/delayed_event_test.go
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
> Fixes to MSC4140 tests

- tests/csapi/account_change_password_test.go
- tests/csapi/account_deactivate_test.go
- tests/csapi/apidoc_room_create_test.go
Hello,
I am using Rust to develop a matrix server-side [Palpo](https://github.com/palpo-matrix-server/palpo), which is based on another web framework I maintain, [Salvo](https://github.com/salvo-rs/salvo/). When using complement for testing, I found that several places seemed to use the old data format, which caused some of my tests to fail. I am not sure whether it needs to be fixed.
Signed-off-by: Chrislearn Young <chris@acroidea.com>
> fix: Use latest data structure for acccount testing

- .github/workflows/ci.yaml
- README.md
- dockerfiles/README.md
At least where it makes sense.
> Update references from matrix-org/dendrite to element-hq/dendrite

- tests/csapi/media_async_uploads_test.go
This fixes support with homeservers that enforce authenticated media, such as Synapse in https://github.com/element-hq/synapse/pull/17889
Signed-off-by: Olivier 'reivilibre' <oliverw@element.io>
> TestAsyncUpload: download with authentication

- tests/csapi/apidoc_content_test.go
- tests/media_filename_test.go
- tests/media_nofilename_test.go
- tests/media_thumbnail_test.go
These will be expected to fail when Synapse enforces authenticated media by default in
https://github.com/element-hq/synapse/pull/17889
Signed-off-by: Olivier 'reivilibre' <oliverw@element.io>
> Skip tests requiring unauthenticated media on Synapse

- tests/csapi/upload_keys_test.go
Per MSC4225, they should be issued in the same order they were uploaded.
> Add test for the order in which OTKs are issued

- client/client.go
Fix being able to re-use request path parts in `MustDo`/`Do`
Previously, this example wouldn't work:
```go
alice := deployment.Register(t, "hs1", helpers.RegistrationOpts{})
roomID := alice.MustCreateRoom(t, map[string]interface{}{
"preset": "public_chat",
})
requestPathParts := []string{"_matrix", "client", "v3", "directory", "list", "room", roomID}
alice.MustDo(t, "GET", requestPathParts)
// 404 because the path is already escaped and will be escaped again
alice.MustDo(t, "GET", requestPathParts)
```
```
client.go:685: [CSAPI] GET hs1/_matrix/client/v3/directory/list/room/!DolNGvQqgiKnDmimTj:hs1 => 200 OK (3.324405ms)
client.go:685: [CSAPI] GET hs1/_matrix/client/v3/directory/list/room/%21DolNGvQqgiKnDmimTj:hs1 => 404 Not Found (3.030919ms)
```
Signed-off-by: Eric Eastwood …
> Fix being able to re-use request path parts in `MustDo`/`Do`

- client/client.go
- tests/csapi/apidoc_profile_displayname_test.go
- tests/csapi/keychanges_test.go
- tests/csapi/upload_keys_test.go
- tests/csapi/user_directory_display_names_test.go
- tests/federation_device_list_update_test.go
- tests/federation_query_profile_test.go
- tests/msc3902/federation_room_join_partial_state_test.go
Small refactor to add a few more helpers. The hitlist for this can be discovered using `grep --only-matching -Er '\[\]string\{\"_matrix\".*\}' tests | grep -E --only-matching '\[\]string.*' | sort | uniq -c | sort` which currently spits out:
```
...
4 []string{"_matrix", "client", "v3", "account", "whoami"}
4 []string{"_matrix", "client", "v3", "devices"}
4 []string{"_matrix", "client", "v3", "directory", "room", aliasName}
4 []string{"_matrix", "client", "v3", "logout"}
4 []string{"_matrix", "client", "v3", "rooms", roomID, "send", "m.room.message", "txn-1"}, client.WithJSONBody(t, map[string]interface{}
4 []string{"_matrix", "client", "v3", "rooms", roomID, "state", "m.room.topic"}
5 []string{"_matrix", "client", "v3", "rooms", roomID, "kick"}
5 []string{"_matrix", "client", "v3", …
```
> Add Must[Get|Set]DisplayName and use MustUploadKeys in more places

- tests/federation_rooms_invite_test.go
- tests/knocking_test.go
Update knock test utilities to be more generic/useful. They now match the style of the other utilities under `client`: `mustKnockOnRoomSynced`/`syncKnockedOn`
This is spawning from trying to write some knock tests that also stressed https://github.com/element-hq/synapse/pull/18075 but they didn't pan out. I thought this refactor and update was still useful to upstream in any case.
Signed-off-by: Eric Eastwood <erice@element.io>
> Update knock test utilities to be more generic/useful

- tests/federation_rooms_invite_test.go
Add remote invite -> join/reject tests for rooms that a homeserver is already participating in
Regression tests for https://github.com/element-hq/synapse/pull/18075
Signed-off-by: Eric Eastwood <erice@element.io>
> Add remote invite -> join/reject tests for rooms that a homeserver is already participating in

- test_main.go
Rather than having `TestMainWithCleanup` and `TestMain`, use functional options. Add support for a custom deployment mechanism at the same time.
This is a breaking change for users who use `TestMainWithCleanup(m, namespace, cleanupFn)` who now need to do `TestMain(m, namespace, complement.WithCleanup(cleanupFn))`.
> Support functional options in TestMain

- tests/msc4140/delayed_event_test.go
Sometimes it can take a while for the `/delayed_events` endpoint  to return new events due to replication lag
> Try and reduce flakey `TestDelayedEvents` tests

- tests/csapi/upload_keys_test.go
It seems that `MustDo` is used incorrectly here, causing the test to fail.
Signed-off-by: Chrislearn Young [chris@acroidea.com](mailto:chris@acroidea.com)
> fix: Use `bob.Do` in test `Rejects invalid device keys`

- federation/server.go
- federation/server_room.go
This allows more experimentation because it allows Complement to make ServerRoom structs for unknown room versions.
> Open up more ServerRoom functions

- config/config.go
- internal/docker/builder.go
- internal/docker/deployer.go
Fix Complement not using `config.HSPortBindingIP` (`127.0.0.1`) for the homeserver `BaseURL`.
Regressed in https://github.com/matrix-org/complement/pull/776 which started using the Docker default `HostIP` (`0.0.0.0`) because we removed the specific `HSPortBindingIP` port bindings for `8008` and `8448` (see "Root cause" section below).
This caused downstream issues in some of our out-of-repo Complement tests (Element internal) which stress some SSO/OIDC login flows with Synapse. 
Before https://github.com/matrix-org/complement/pull/776, [`SsoRedirectServlet`](https://github.com/element-hq/synapse/blob/33ba8860c43d4770ea119a09a4fcbbf366f3b32e/synapse/rest/client/login.py#L645-L683) received a request like this `http://127.0.0.1:8008/_matrix/client/v3/login/sso/redirect/oidc-test_idp?redirect …
> Fix Complement not using `HSPortBindingIP` (`127.0.0.1`) for the homeserver `BaseURL`

- ONBOARDING.md
- README.md
We no longer use build tags for unstable MSCs as of #666. It's confusing to have documentation still reference them.
This PR also adds documentation specifically for writing tests for unstable MSCs. Today, we use go packages.
> Update documentation for writing tests for unstable MSCs

- tests/federation_room_get_missing_events_test.go
See https://github.com/element-hq/synapse/pull/18746 - discovered via Chaos testing.
> Regression test for corrupted auth chains

- tests/room_timestamp_to_event_test.go
> Fix typos.

- tests/federation_rooms_invite_test.go
c.f. https://github.com/element-hq/synapse/pull/18823
> Test that invites can be rescinded over federation

- .github/workflows/ci.yaml
- client/client.go
- tests/csapi/thread_notifications_test.go
- tests/msc3930/msc3930_test.go
- tests/msc4306/main_test.go
- tests/msc4306/thread_subscriptions_test.go
Pairs with: https://github.com/element-hq/synapse/pull/18819
---
Signed-off-by: Olivier 'reivilibre' <oliverw@matrix.org>
> MSC4306: Thread Subscriptions Tests

- tests/federation_acl_test.go
Found a new event that should be using the `deployment.GetFullyQualifiedHomeserverName(t, hsName)` helper -> `m.room.server_acl` events
Follow-up to https://github.com/matrix-org/complement/pull/780
Signed-off-by: Eric Eastwood <erice@element.io>
> Use `deployment.GetFullyQualifiedHomeserverName(t, hsName)` helper on `m.room.server_acl` events

- client/client.go
- internal/docker/deployment.go
To reduce the chance of multiple rooms being made in the same millisecond which makes v12 rooms unhappy as it causes the same room ID to be generated. This causes flakey tests on v12.
> Lock /createRoom calls

- tests/csapi/device_lists_test.go
This field is required by the spec: https://spec.matrix.org/v1.16/client-server-api/#post_matrixclientv3keysupload
Was causing failing tests on https://github.com/element-hq/synapse/pull/17097.
> Add require `signatures` field to `/keys/upload` call
