matrix-org/complement

ONBOARDING.md
README.md

Some documentation fixes justified in github comments. Overall this documentation is excellent. I haven't tried converting/writing a test yet, but the information already available is very helpful.

Fix up and modify some bits of the documentation

---

internal/config/config.go
internal/docker/builder.go

There's probably a better/smarter way to do this, but for now this seems like the easy route.

Support an environment variable to specify a longer startup period

---

dockerfiles/dendrite.yaml

This updates `dendrite.yaml` to the new format.

Update Dendrite config to version 1

---

internal/instruction/runner.go

Fixes #38.
This PR allows federating homeservers to create and join other's rooms during blueprint execution. This originally did not work for homeservers which did not extract a `server_name` from a Room ID during room join, such as Synapse.
We now accomplish this by storing the server's name tied to the room's reference when creating the room, and when joining the room look up that server name using the reference.
I reused the `.var_name` system here to indicate a variable, even though we aren't digging through any JSON. I'm open to discussion around that though.

Use server_name query parameters when joining rooms during blueprint execution

---

internal/instruction/runner.go

- Add configurable `concurrency int` which sets the max number of simultaneous goroutines
- Users can be created in any order provided they haven't been made before, so % len based
on the localpart
- Rooms can only be created after all users have been created
- Rooms can be created in any order provided all events are created in order, so % len based
on the room index

Parallelise the blueprint instruction runner

---

tests/apidoc_request_encoding_test.go

This tests add the following sestets https://github.com/matrix-org/sytest/blob/develop/tests/10apidoc/01request-encoding.pl in Golang

test: add test for request_encoding

---

README.md
tests/apidoc_login_test.go

Signed-off-by: meenal <meenal@Meenal-MacBook-Pro.local>

feat: add login tests

---

tests/apidoc_login_test.go

tests: add GET /login test

---

tests/apidoc_login_test.go

tests: POST /login returns same device_id

---

tests/apidoc_login_test.go

tests: add all login tests

---

tests/apidoc_version_test.go

tests: add version structure tests

---

.github/workflows/ci.yaml
tests/apidoc_login_test.go
tests/apidoc_presence_test.go

tests: add user_presence tests

---

tests/sync_filter_test.go

tests: add can create filter test

---

internal/client/client.go
internal/docker/deployment.go
tests/account_change_password_test.go
tests/apidoc_login_test.go

feat: add tests for password change

---

tests/apidoc_presence_test.go

feat: Implement remaining presence test

---

tests/account_change_password_test.go

feat: add more change_password_tests

---

tests/sync_filter_test.go

feat: implement all filter tests

---

tests/account_deactivate_test.go

feat: add account deactivate tests

---

tests/msc3083_test.go

Corresponding Synapse PR: matrix-org/synapse#10189.

Update tests for changes to MSC3083.

---

README.md
tests/account_change_password_test.go

feat: session related change-password tests

---

tests/apidoc_profile_displayname_test.go

feat: add display name test

---

tests/apidoc_profile_avatar_url_test.go

feat: add avatar_url tests

---

internal/federation/server.go

If we can't start our test federation server, there's no point going on.
(I seem to keep forgetting to shut down the thing I have on port 8448 and then wondering why my test is failing.)

Bomb out sooner if we cannot start a federation server

---

dockerfiles/SynapseWorkers.Dockerfile

The comment was old (back when this file was in the Synapse repo) and not very helpful for actually building the image. The linked doc (which granted is hard to find on its own currently) should be helpful for those trying to use this.

Link to instructions on how to build SynapseWorker image

---

tests/apidoc_room_create_test.go

feat: add tests to check room_create errors

---

tests/apidoc_room_create_test.go

feat: implement all room_create tests

---

internal/instruction/runner.go

https://github.com/matrix-org/complement/pull/160/files?w=1

Handle failures in bestEffort mode without panicking

---

dockerfiles/Dendrite.Dockerfile
dockerfiles/DendritePostgres.Dockerfile

Go 1.15 for Dendrite docker images

---

tests/apidoc_room_state_test.go

feat: implement additional room_state tests

---

internal/client/client.go

Fixes #170
Timeout:
```
TestRoomCreationReportsEventsToMyself/parallel/Room_creation_reports_m.room.create_to_myself: client.go:368: GET hs1/_matrix/client/r0/sync => 200 OK (1.00417649s)
TestRoomCreationReportsEventsToMyself/parallel/Room_creation_reports_m.room.create_to_myself: client.go:368: GET hs1/_matrix/client/r0/sync => 200 OK (1.007952344s)
TestRoomCreationReportsEventsToMyself/parallel/Room_creation_reports_m.room.create_to_myself: client.go:368: GET hs1/_matrix/client/r0/sync => 200 OK (1.004654072s)
TestRoomCreationReportsEventsToMyself/parallel/Room_creation_reports_m.room.create_to_myself: client.go:368: GET hs1/_matrix/client/r0/sync => 200 OK (1.005179858s)
TestRoomCreationReportsEventsToMyself/parallel/Room_creation_reports_m.room.create_to_myself: client.go:368: GET …
```

Print the failing event in the event of t.Fatalf

---

cmd/sytest-coverage/main.go

fix: script to count the number of converted tests

---

tests/msc2946_test.go

And the conversation in matrix-org/matrix-doc#1898.
Corresponds to matrix-org/synapse#10579.

Update the pagination parameter name based on MSC2946 review.

---

tests/csapi/apidoc_room_members_test.go

feat: add room_membership tests

---

cmd/sytest-coverage/main.go

Minor update to the coverage tool, so there's no need to specify new test folders. (which could be forgotten)

Minor update to the converted tests tool

---

tests/csapi/user_query_keys_test.go

After my changes in matrix-org/synapse#10593

Unblacklist user_query_keys_test for synapse

---

dockerfiles/SynapseWorkers.Dockerfile

Otherwise the box doesn't start.
Vaguely related to matrix-org/synapse#10065.

Bump the postgres version used by Synapse workers to 13.

---

internal/federation/server_room.go
tests/federation_room_invite_test.go

As per https://github.com/matrix-org/complement/pull/131/files#r658674594
Fixes #137

Add ServerRoom.MustHaveMembershipForUser

---

internal/client/client.go
tests/csapi/apidoc_room_members_test.go

This;
- adds the sytest test for SYN-442: "Test that we can be reinvited to a room we created"
- adds `SyncUntilJoined` helper function

Add test for SYN-442

---

.github/workflows/ci.yaml
README.md
dockerfiles/ComplementCIBuildkite.Dockerfile
tests/csapi/account_deactivate_test.go

Update to use gotestfmt in complement CI

---

internal/docker/deployer.go

I was looking through Complement's deploy process and noticed that we sequentially started containers on `Deploy()`. We can and should be doing this in parallel.
This should halve the time it takes to deploy federation tests, and given deploying the containers is by far the largest contributor to time in the tests, this should roughly halve the runtime of federation tests. CSAPI tests are unaffected as they only have 1 homeserver in the `Deployment`.

Parallelise deployments of multiple HSes

---

internal/client/client.go
tests/csapi/sync_test.go

Fixes https://github.com/matrix-org/complement/issues/25
Adds `SyncLeftFrom`
cc @neilalexander

Address matrix-org/dendrite#1394 bugs

---

internal/docker/builder.go
internal/docker/deployer.go

I was trying to figure out what was going on during container setup, so added some extra logging.

Additional debug logging for HS setup

---

tests/federation_room_get_missing_events_test.go
tests/msc2836_test.go

Just a sanity check on the timeline which was missing.

Ensure we get events in the right order

---

dockerfiles/Dendrite.Dockerfile
tests/csapi/sync_test.go

Fixing this and realising it was still flakey led to discovering https://github.com/matrix-org/dendrite/pull/2137

TestTentativeEventualJoiningAfterRejecting: retry syncing to stop flakey test

---

tests/csapi/apidoc_room_forget_test.go

Somehow chaining `.Get` seems to be the problem, not the escape part (I added it anyway).

Fix flakey room forget tests

---

tests/room_hierarchy_test.go

xref https://github.com/matrix-org/dendrite/pull/2232

Enable some MSC2946 tests for dendrite

---

tests/csapi/account_change_password_pushers_test.go
tests/csapi/account_change_password_test.go
tests/csapi/apidoc_device_management_test.go

Adds the missing `DELETE /device` tests.

Add missing device management tests

---

tests/csapi/apidoc_room_members_test.go

10apidoc/33room-members 8/8 tests

Add 10apidoc/33room-members tests

---

tests/csapi/apidoc_room_members_test.go

Ensure we receive a ban event on `/sync` before asking `/rooms/{roomID}/state` for the actual state.

Deflake ban test

---

tests/csapi/apidoc_login_test.go

Test for https://github.com/matrix-org/dendrite/issues/2287 / https://github.com/matrix-org/dendrite/pull/2292

Add regression test for Dendrite issue #2287

---

tests/csapi/room_messages_test.go

as https://github.com/matrix-org/dendrite/issues/2257 has closed

unskip TestRoomMessagesLazyLoading on dendrite

---

.github/workflows/ci.yaml
internal/federation/server.go
internal/federation/server_test.go
tests/msc2836_test.go

With internal test to assert this.

Fix #355: ensure Complement's server is signed correctly

---

tests/csapi/rooms_state_test.go

I'm fed up with this failing the whole time.

Blacklist a failing test on dendrite

---

tests/csapi/power_levels_test.go

xref https://github.com/matrix-org/gomatrixserverlib/pull/306

Add regression test when modifying events_default

---

tests/restricted_rooms_test.go

Paired with matrix-org/dendrite#2478.

Allow some of the restricted rooms tests for Dendrite

---

README.md

Document use with `ufw`

---

tests/federation_room_join_partial_state_test.go

See https://github.com/matrix-org/synapse/issues/12645

Add test for a gappy sync across de-partial stating of a room

---

.github/CODEOWNERS

I'm not sure we necessarily want this, but it seems like the reasonable thing to do for this repo?

Request review from Synapse & Dendrite teams.

---

tests/federation_room_join_partial_state_test.go

Regression test for https://github.com/matrix-org/synapse/issues/13411

Faster joins: test that events stay rejected

---

internal/docker/builder.go
internal/docker/deployer.go

Some minor tweaks to the error handling here

Improve error handling when spinning up homeservers

---

tests/csapi/apidoc_search_test.go

https://github.com/matrix-org/dendrite/pull/2675 was merged recently.

Don't skip `/search` tests on Dendrite

---

tests/csapi/apidoc_room_history_visibility_test.go

as https://github.com/matrix-org/dendrite/issues/617 has been resolved

Remove dendrite skips in history visibility tests 

---

.github/workflows/ci.yaml

Handle gotestfmt repository move

---

tests/csapi/room_typing_test.go

This adds 1 sytest:
- `./tests/90jira/SYN-328.pl:multi_test "Typing notifications don't leak",`

Sytest: Add `90jira/SYN-328` test

---

tests/csapi/rooms_members_local_test.go

Adds a test from `tests/30rooms/52members.pl`

Add "Can get members at a given point" test

---

.github/workflows/ci.yaml
tests/csapi/room_messages_relation_filter_test.go

Requires matrix-org/synapse#14339 to properly enable the features.

Add tests for MSC3874, filtering messages by relation type

---

tests/federation_room_get_missing_events_test.go

Adds `Inbound federation can return missing events for $vis visibility` from `tests/50federation/33room-get-missing-events.pl`

Add tests for /get_missing_events

---

tests/csapi/room_members_test.go
tests/csapi/rooms_members_local_test.go

This field is required and it seems that the matrix-js-sdk is unable to correctly encrypt messages without it.
Makes sure we have that field in the response to `/members`.
Also removes a duplicate test.

Check `room_id` in `/members` responses

---

tests/federation_room_join_partial_state_test.go

This PR adds some code to check that a message sent during a room in partial state correctly triggers a federation request to be received by the other server.

Check that message sent during fast join triggers a fed request

---

dockerfiles/README.md
runtime/hs.go
runtime/hs_conduit.go

Add Conduit to the recognised Complement homeservers

---

internal/instruction/runner.go

Otherwise we'll stop the HS half way through a join, which can cause issues in the actual test.

Wait for room to be fully created in blueprints

---

tests/federation_room_join_partial_state_test.go

Add test to determine that the public room list is correctly updated after lazy load finishes syncing state

---

.github/workflows/ci.yaml

Whoops! Follow-up to #598 
Hopefully fixes the problem seen in https://github.com/matrix-org/complement/actions/runs/4108255185

Only require sign-off on PRS

---

.editorconfig

editorconfig: init

---

tests/federation_room_join_partial_state_test.go

It can take some time for a room to appear in the public room
directory after joining it, even after the request to add the room
to the directory has completed. Add retry logic to check the public room
directory for 3 seconds before giving up.
---
Fixes https://github.com/matrix-org/synapse/issues/15006.

Faster room joins: Deflake test for room stats update once synced

---

README.md

readme: update Sytest parity section

---

tests/federation_acl_test.go

Test for https://github.com/matrix-org/dendrite/issues/3004

Add federation ACL test

---

tests/federation_upload_keys_test.go

I think these tests were somehow interacting with each other poorly when run in parallel, leading to flakes. They are only two tests so may as well try removing the parallel bit and seeing if it helps

Fix flakey test due to incorrectly running in parallel

---

go.mod
go.sum
internal/docker/builder.go
internal/docker/deployer.go
internal/docker/deployment.go
runtime/hs_dendrite.go
test_package.go

Required if we want to hook into testcontainers

Update docker dependency

---

client/client.go
tests/csapi/media_async_uploads_test.go

async uploads: add tests

---

tests/federation_device_list_update_test.go

Add device list update tests over federation

---

tests/knocking_test.go

Add a test for invite->knock transitions
